// codegen — C transpilation backend
//
// walks the type-checked AST and emits C source code. the generated C
// is compiled by `zig cc` to produce a native binary.
//
// the emitter does a single pass over the module:
//   1. emit #include and forward declarations
//   2. emit struct/enum type definitions
//   3. emit function definitions
//
// type mapping:
//   Int    → int64_t        Float  → double
//   Bool   → bool           String → forge_string_t
//   Void   → void           sized ints → stdint types
//
// the emitter assumes the AST has been type-checked. it uses the type
// table from the checker to resolve types for expressions, struct
// fields, etc.

const std = @import("std");
const ast = @import("ast.zig");
const types = @import("types.zig");
const Checker = @import("checker.zig");

const TypeId = types.TypeId;
const TypeTable = types.TypeTable;
const Type = types.Type;
const Scope = Checker.Scope;

// ---------------------------------------------------------------
// C emitter
// ---------------------------------------------------------------

/// errors that can occur during C emission. limited to allocation
/// failures since we're just building a string buffer.
pub const EmitError = std.mem.Allocator.Error;

pub const CEmitter = struct {
    output: std.ArrayList(u8),
    indent_level: u32,
    type_table: *const TypeTable,
    module_scope: *const Scope,
    allocator: std.mem.Allocator,
    /// tracks variable types in the current function scope so we can
    /// choose the right C type for bindings and string operations.
    local_types: std.StringHashMap(TypeId),
    /// the return type of the current function being emitted. used to
    /// determine when match arms need `return` prepended.
    current_fn_return: TypeId,
    /// method type information from the checker. key is "TypeName.methodName",
    /// value has the function type id and original AST decl.
    method_types: *const std.StringHashMap(Checker.MethodEntry),
    /// counter for generating unique loop index variable names (__idx_0, __idx_1, ...)
    for_counter: u32,

    pub fn init(
        allocator: std.mem.Allocator,
        type_table: *const TypeTable,
        module_scope: *const Scope,
        method_types: *const std.StringHashMap(Checker.MethodEntry),
    ) CEmitter {
        return .{
            .output = .empty,
            .indent_level = 0,
            .type_table = type_table,
            .module_scope = module_scope,
            .allocator = allocator,
            .local_types = std.StringHashMap(TypeId).init(allocator),
            .current_fn_return = .void,
            .method_types = method_types,
            .for_counter = 0,
        };
    }

    pub fn deinit(self: *CEmitter) void {
        self.local_types.deinit();
        self.output.deinit(self.allocator);
    }

    /// get the generated C source as a string slice.
    pub fn getOutput(self: *const CEmitter) []const u8 {
        return self.output.items;
    }

    // ---------------------------------------------------------------
    // module emission
    // ---------------------------------------------------------------

    /// emit a complete C translation unit from a forge module.
    pub fn emitModule(self: *CEmitter, module: *const ast.Module) EmitError!void {
        try self.emitPreamble();

        // pass 1: struct type definitions (must come before function decls
        // since functions may use struct types in signatures)
        for (module.decls) |*decl| {
            switch (decl.kind) {
                .struct_decl => |*sd| try self.emitStructDef(sd),
                else => {},
            }
        }

        // pass 2: enum type definitions
        for (module.decls) |*decl| {
            switch (decl.kind) {
                .enum_decl => |*ed| try self.emitEnumDef(ed),
                else => {},
            }
        }

        // pass 3: forward-declare all functions
        for (module.decls) |*decl| {
            switch (decl.kind) {
                .fn_decl => |*fd| try self.emitFnForwardDecl(fd),
                else => {},
            }
        }

        // pass 3b: forward-declare methods from impl blocks
        for (module.decls) |*decl| {
            switch (decl.kind) {
                .impl_decl => |impl_d| try self.emitImplForwardDecls(&impl_d),
                else => {},
            }
        }
        try self.writeByte('\n');

        // pass 4: function definitions
        for (module.decls) |*decl| {
            switch (decl.kind) {
                .fn_decl => |*fd| try self.emitFnDef(fd),
                else => {},
            }
        }

        // pass 5: method definitions from impl blocks
        for (module.decls) |*decl| {
            switch (decl.kind) {
                .impl_decl => |impl_d| try self.emitImplMethodDefs(&impl_d),
                else => {},
            }
        }
    }

    fn emitPreamble(self: *CEmitter) EmitError!void {
        try self.writeStr("// generated by forge compiler — do not edit\n");
        try self.writeStr("#include \"forge_runtime.h\"\n\n");
    }

    // ---------------------------------------------------------------
    // struct definitions
    // ---------------------------------------------------------------

    fn emitStructDef(self: *CEmitter, sd: *const ast.StructDecl) EmitError!void {
        // skip generic (uninstantiated) structs
        if (sd.generic_params.len > 0) return;

        try self.writeStr("typedef struct {\n");
        self.indent_level += 1;
        for (sd.fields) |field| {
            try self.writeIndent();
            try self.emitCType(self.resolveFieldType(sd.name, field.name));
            try self.writeByte(' ');
            try self.writeStr(field.name);
            try self.writeStr(";\n");
        }
        self.indent_level -= 1;
        try self.writeStr("} ");
        try self.writeStr(sd.name);
        try self.writeStr(";\n\n");
    }

    /// look up the type of a struct field from the type table.
    fn resolveFieldType(self: *const CEmitter, struct_name: []const u8, field_name: []const u8) TypeId {
        const type_id = self.type_table.lookup(struct_name) orelse return .err;
        const ty = self.type_table.get(type_id) orelse return .err;
        const fields = switch (ty) {
            .@"struct" => |s| s.fields,
            else => return .err,
        };
        for (fields) |field| {
            if (std.mem.eql(u8, field.name, field_name)) return field.type_id;
        }
        return .err;
    }

    // ---------------------------------------------------------------
    // enum definitions
    // ---------------------------------------------------------------

    fn emitEnumDef(self: *CEmitter, ed: *const ast.EnumDecl) EmitError!void {
        // skip generic (uninstantiated) enums
        if (ed.generic_params.len > 0) return;

        // tag enum
        try self.writeStr("typedef enum {\n");
        self.indent_level += 1;
        for (ed.variants) |variant| {
            try self.writeIndent();
            try self.writeStr(ed.name);
            try self.writeStr("_TAG_");
            try self.writeStr(variant.name);
            try self.writeStr(",\n");
        }
        self.indent_level -= 1;
        try self.writeStr("} ");
        try self.writeStr(ed.name);
        try self.writeStr("_Tag;\n\n");

        // tagged union struct
        try self.writeStr("typedef struct {\n");
        self.indent_level += 1;
        try self.writeIndent();
        try self.writeStr(ed.name);
        try self.writeStr("_Tag tag;\n");

        // union of variant data (only if any variant has fields)
        var has_data = false;
        for (ed.variants) |variant| {
            if (variant.fields.len > 0) {
                has_data = true;
                break;
            }
        }

        if (has_data) {
            try self.writeIndent();
            try self.writeStr("union {\n");
            self.indent_level += 1;
            for (ed.variants) |variant| {
                if (variant.fields.len > 0) {
                    try self.writeIndent();
                    try self.writeStr("struct {\n");
                    self.indent_level += 1;
                    for (variant.fields, 0..) |_, i| {
                        try self.writeIndent();
                        const field_tid = self.resolveEnumFieldType(ed.name, variant.name, i);
                        try self.emitCType(field_tid);
                        try self.writeFmt(" _{d};\n", .{i});
                    }
                    self.indent_level -= 1;
                    try self.writeIndent();
                    try self.writeStr("} ");
                    try self.writeStr(variant.name);
                    try self.writeStr(";\n");
                }
            }
            self.indent_level -= 1;
            try self.writeIndent();
            try self.writeStr("} data;\n");
        }

        self.indent_level -= 1;
        try self.writeStr("} ");
        try self.writeStr(ed.name);
        try self.writeStr(";\n\n");
    }

    /// resolve the type of an enum variant field from the type table.
    fn resolveEnumFieldType(self: *const CEmitter, enum_name: []const u8, variant_name: []const u8, field_idx: usize) TypeId {
        const type_id = self.type_table.lookup(enum_name) orelse return .err;
        const ty = self.type_table.get(type_id) orelse return .err;
        const variants = switch (ty) {
            .@"enum" => |e| e.variants,
            else => return .err,
        };
        for (variants) |variant| {
            if (std.mem.eql(u8, variant.name, variant_name)) {
                if (field_idx < variant.fields.len) return variant.fields[field_idx];
                return .err;
            }
        }
        return .err;
    }

    // ---------------------------------------------------------------
    // function declarations
    // ---------------------------------------------------------------

    fn emitFnForwardDecl(self: *CEmitter, fd: *const ast.FnDecl) EmitError!void {
        // skip generic (uninstantiated) functions
        if (fd.generic_params.len > 0) return;

        // main is special — we emit it as int main(void)
        if (std.mem.eql(u8, fd.name, "main")) {
            try self.writeStr("int main(void);\n");
            return;
        }

        try self.emitReturnType(fd.return_type);
        try self.writeByte(' ');
        try self.emitUserFnName(fd.name);
        try self.emitParamList(fd.params);
        try self.writeStr(";\n");
    }

    // ---------------------------------------------------------------
    // impl block emission
    // ---------------------------------------------------------------

    /// extract the concrete type name from an impl decl. the parser's
    /// naming is inverted: `impl Display for Point:` has target=Display,
    /// interface=Point. `impl Point:` has target=Point, interface=null.
    fn implTypeName(impl_d: *const ast.ImplDecl) ?[]const u8 {
        if (impl_d.interface) |iface_type_expr| {
            // `impl X for Y:` — Y is the concrete type
            return switch (iface_type_expr.kind) {
                .named => |n| n,
                else => null,
            };
        } else {
            // `impl X:` — X is the concrete type
            return switch (impl_d.target.kind) {
                .named => |n| n,
                else => null,
            };
        }
    }

    /// emit forward declarations for all methods in an impl block.
    fn emitImplForwardDecls(self: *CEmitter, impl_d: *const ast.ImplDecl) EmitError!void {
        const type_name = implTypeName(impl_d) orelse return;
        for (impl_d.methods) |method| {
            try self.emitMethodForwardDecl(type_name, &method.decl);
        }
    }

    /// emit a single method forward declaration.
    /// `fn distance_from_origin() -> Int` on Point becomes:
    /// `int64_t Point_distance_from_origin(Point self);`
    fn emitMethodForwardDecl(self: *CEmitter, type_name: []const u8, fd: *const ast.FnDecl) EmitError!void {
        if (fd.generic_params.len > 0) return;
        try self.emitReturnType(fd.return_type);
        try self.writeByte(' ');
        try self.writeStr(type_name);
        try self.writeByte('_');
        try self.writeStr(fd.name);
        // emit param list with `self` as first parameter
        try self.writeByte('(');
        try self.writeStr(type_name);
        try self.writeStr(" self");
        for (fd.params) |param| {
            try self.writeStr(", ");
            if (param.type_expr) |te| {
                try self.emitTypeExpr(te);
            } else {
                try self.writeStr("/* unknown */");
            }
            try self.writeByte(' ');
            try self.writeStr(param.name);
        }
        try self.writeByte(')');
        try self.writeStr(";\n");
    }

    /// emit method definitions for all methods in an impl block.
    fn emitImplMethodDefs(self: *CEmitter, impl_d: *const ast.ImplDecl) EmitError!void {
        const type_name = implTypeName(impl_d) orelse return;
        for (impl_d.methods) |method| {
            try self.emitMethodDef(type_name, &method.decl);
        }
    }

    /// emit a single method definition as a C function.
    /// `self` becomes the first explicit parameter of the struct type.
    fn emitMethodDef(self: *CEmitter, type_name: []const u8, fd: *const ast.FnDecl) EmitError!void {
        if (fd.generic_params.len > 0) return;

        // clear local type tracking
        self.local_types.clearRetainingCapacity();

        // track return type for match tail-position returns
        self.current_fn_return = if (fd.return_type) |rt|
            self.resolveTypeExprToId(rt)
        else
            .void;

        // register `self` as local with the struct's type
        const self_tid = self.type_table.lookup(type_name) orelse .err;
        self.local_types.put("self", self_tid) catch {};

        // register method parameters
        for (fd.params) |param| {
            if (param.type_expr) |te| {
                const tid = self.resolveTypeExprToId(te);
                self.local_types.put(param.name, tid) catch {};
            }
        }

        // emit signature
        try self.emitReturnType(fd.return_type);
        try self.writeByte(' ');
        try self.writeStr(type_name);
        try self.writeByte('_');
        try self.writeStr(fd.name);
        try self.writeByte('(');
        try self.writeStr(type_name);
        try self.writeStr(" self");
        for (fd.params) |param| {
            try self.writeStr(", ");
            if (param.type_expr) |te| {
                try self.emitTypeExpr(te);
            } else {
                try self.writeStr("/* unknown */");
            }
            try self.writeByte(' ');
            try self.writeStr(param.name);
        }
        try self.writeStr(") {\n");

        self.indent_level += 1;
        try self.emitBlock(&fd.body);
        self.indent_level -= 1;
        try self.writeStr("}\n\n");
    }

    fn emitFnDef(self: *CEmitter, fd: *const ast.FnDecl) EmitError!void {
        // skip generic functions
        if (fd.generic_params.len > 0) return;

        // clear local type tracking for each function
        self.local_types.clearRetainingCapacity();

        // track the function's return type so match arms can emit `return`
        self.current_fn_return = if (fd.return_type) |rt|
            self.resolveTypeExprToId(rt)
        else
            .void;

        // register parameters as local variables
        for (fd.params) |param| {
            if (param.type_expr) |te| {
                const tid = self.resolveTypeExprToId(te);
                self.local_types.put(param.name, tid) catch {};
            }
        }

        if (std.mem.eql(u8, fd.name, "main")) {
            try self.writeStr("int main(void) {\n");
        } else {
            try self.emitReturnType(fd.return_type);
            try self.writeByte(' ');
            try self.emitUserFnName(fd.name);
            try self.emitParamList(fd.params);
            try self.writeStr(" {\n");
        }

        self.indent_level += 1;
        try self.emitBlock(&fd.body);

        // if main, add return 0
        if (std.mem.eql(u8, fd.name, "main")) {
            try self.writeIndent();
            try self.writeStr("return 0;\n");
        }

        self.indent_level -= 1;
        try self.writeStr("}\n\n");
    }

    /// emit a user-defined function name, prefixed to avoid collisions
    /// with C standard library names (abs, div, etc).
    fn emitUserFnName(self: *CEmitter, name: []const u8) EmitError!void {
        try self.writeStr("fg_");
        try self.writeStr(name);
    }

    fn emitReturnType(self: *CEmitter, return_type: ?*const ast.TypeExpr) EmitError!void {
        if (return_type) |rt| {
            try self.emitTypeExpr(rt);
        } else {
            try self.writeStr("void");
        }
    }

    fn emitParamList(self: *CEmitter, params: []const ast.Param) EmitError!void {
        try self.writeByte('(');
        if (params.len == 0) {
            try self.writeStr("void");
        } else {
            for (params, 0..) |param, i| {
                if (i > 0) try self.writeStr(", ");
                if (param.type_expr) |te| {
                    try self.emitTypeExpr(te);
                } else {
                    try self.writeStr("/* unknown */");
                }
                try self.writeByte(' ');
                try self.writeStr(param.name);
            }
        }
        try self.writeByte(')');
    }

    // ---------------------------------------------------------------
    // block and statements
    // ---------------------------------------------------------------

    fn emitBlock(self: *CEmitter, block: *const ast.Block) EmitError!void {
        for (block.stmts) |*stmt| {
            try self.emitStmt(stmt);
        }
    }

    fn emitStmt(self: *CEmitter, stmt: *const ast.Stmt) EmitError!void {
        switch (stmt.kind) {
            .binding => |b| try self.emitBinding(&b),
            .assignment => |a| try self.emitAssignment(&a),
            .if_stmt => |ifs| try self.emitIfStmt(&ifs),
            .while_stmt => |ws| try self.emitWhileStmt(&ws),
            .return_stmt => |rs| try self.emitReturnStmt(&rs),
            .break_stmt => {
                try self.writeIndent();
                try self.writeStr("break;\n");
            },
            .continue_stmt => {
                try self.writeIndent();
                try self.writeStr("continue;\n");
            },
            .expr_stmt => |expr| {
                try self.writeIndent();
                try self.emitExpr(expr);
                try self.writeStr(";\n");
            },
            .match_stmt => |m| try self.emitMatchStmt(&m),
            .for_stmt => |fs| try self.emitForStmt(&fs),
            .fail_stmt => |_| {
                // fail not yet supported in codegen
                try self.writeIndent();
                try self.writeStr("/* fail not yet supported */\n");
            },
        }
    }

    fn emitBinding(self: *CEmitter, b: *const ast.Binding) EmitError!void {
        // determine the type and track it for later lookups
        const tid = if (b.type_expr) |te|
            self.resolveTypeExprToId(te)
        else
            self.inferExprType(b.value);
        self.local_types.put(b.name, tid) catch {};

        try self.writeIndent();
        if (b.type_expr) |te| {
            try self.emitTypeExpr(te);
        } else if (!tid.isErr()) {
            try self.emitCType(tid);
        } else {
            // fallback: infer from expression structure
            try self.emitTypeForExpr(b.value);
        }
        try self.writeByte(' ');
        try self.writeStr(b.name);
        try self.writeStr(" = ");
        try self.emitExpr(b.value);
        try self.writeStr(";\n");
    }

    /// emit a C type string for an expression by inferring its TypeId.
    /// replaces the old emitInferredType — delegates to inferExprType
    /// which already handles all expression kinds.
    fn emitTypeForExpr(self: *CEmitter, expr: *const ast.Expr) EmitError!void {
        const tid = self.inferExprType(expr);
        if (!tid.isErr()) {
            try self.writeStr(self.cTypeStringForId(tid));
        } else {
            try self.writeStr("/* unknown */");
        }
    }

    fn emitAssignment(self: *CEmitter, a: *const ast.Assignment) EmitError!void {
        try self.writeIndent();
        try self.emitExpr(a.target);
        switch (a.op) {
            .assign => try self.writeStr(" = "),
            .add => try self.writeStr(" += "),
            .sub => try self.writeStr(" -= "),
            .mul => try self.writeStr(" *= "),
            .div => try self.writeStr(" /= "),
        }
        try self.emitExpr(a.value);
        try self.writeStr(";\n");
    }

    fn emitIfStmt(self: *CEmitter, ifs: *const ast.IfStmt) EmitError!void {
        try self.writeIndent();
        try self.writeStr("if (");
        try self.emitExpr(ifs.condition);
        try self.writeStr(") {\n");
        self.indent_level += 1;
        try self.emitBlock(&ifs.then_block);
        self.indent_level -= 1;

        for (ifs.elif_branches) |*elif| {
            try self.writeIndent();
            try self.writeStr("} else if (");
            try self.emitExpr(elif.condition);
            try self.writeStr(") {\n");
            self.indent_level += 1;
            try self.emitBlock(&elif.block);
            self.indent_level -= 1;
        }

        if (ifs.else_block) |*eb| {
            try self.writeIndent();
            try self.writeStr("} else {\n");
            self.indent_level += 1;
            try self.emitBlock(eb);
            self.indent_level -= 1;
        }

        try self.writeIndent();
        try self.writeStr("}\n");
    }

    fn emitWhileStmt(self: *CEmitter, ws: *const ast.WhileStmt) EmitError!void {
        try self.writeIndent();
        try self.writeStr("while (");
        try self.emitExpr(ws.condition);
        try self.writeStr(") {\n");
        self.indent_level += 1;
        try self.emitBlock(&ws.body);
        self.indent_level -= 1;
        try self.writeIndent();
        try self.writeStr("}\n");
    }

    fn emitReturnStmt(self: *CEmitter, rs: *const ast.ReturnStmt) EmitError!void {
        try self.writeIndent();
        if (rs.value) |val| {
            try self.writeStr("return ");
            try self.emitExpr(val);
            try self.writeStr(";\n");
        } else {
            try self.writeStr("return;\n");
        }
    }

    fn emitForStmt(self: *CEmitter, fs: *const ast.ForStmt) EmitError!void {
        const iter_tid = self.inferExprType(fs.iterable);
        const collection_type = if (!iter_tid.isErr()) self.type_table.get(iter_tid) else null;

        // determine the index variable name — user-provided or generated
        var idx_buf: [32]u8 = undefined;
        const idx_name = if (fs.index) |idx| idx else blk: {
            const name = std.fmt.bufPrint(&idx_buf, "__idx_{d}", .{self.for_counter}) catch return;
            self.for_counter += 1;
            break :blk name;
        };

        if (collection_type) |ct| {
            switch (ct) {
                .list => |l| {
                    // for item in list:  →  for (i = 0; i < list.len; i++) { T item = ...; }
                    const elem_c = self.cTypeStringForId(l.element);
                    try self.writeIndent();
                    try self.writeFmt("for (int64_t {s} = 0; {s} < ", .{ idx_name, idx_name });
                    try self.emitExpr(fs.iterable);
                    try self.writeFmt(".len; {s}++) {{\n", .{idx_name});
                    self.indent_level += 1;
                    try self.writeIndent();
                    try self.writeStr(elem_c);
                    try self.writeFmt(" {s} = FORGE_LIST_GET(", .{fs.binding});
                    try self.emitExpr(fs.iterable);
                    try self.writeStr(", ");
                    try self.writeStr(elem_c);
                    try self.writeFmt(", {s});\n", .{idx_name});
                    // track the binding type so the body can use it
                    self.local_types.put(fs.binding, l.element) catch {};
                    if (fs.index != null) self.local_types.put(idx_name, .int) catch {};
                    try self.emitBlock(&fs.body);
                    self.indent_level -= 1;
                    try self.writeIndent();
                    try self.writeStr("}\n");
                },
                .map => |m| {
                    // for key in map:  →  for (i = 0; i < map.len; i++) { K key = ...; }
                    const key_c = self.cTypeStringForId(m.key);
                    try self.writeIndent();
                    try self.writeFmt("for (int64_t {s} = 0; {s} < ", .{ idx_name, idx_name });
                    try self.emitExpr(fs.iterable);
                    try self.writeFmt(".len; {s}++) {{\n", .{idx_name});
                    self.indent_level += 1;
                    try self.writeIndent();
                    try self.writeStr(key_c);
                    try self.writeFmt(" {s} = (({s} *)", .{ fs.binding, key_c });
                    try self.emitExpr(fs.iterable);
                    try self.writeFmt(".keys)[{s}];\n", .{idx_name});
                    self.local_types.put(fs.binding, m.key) catch {};
                    if (fs.index != null) self.local_types.put(idx_name, .int) catch {};
                    try self.emitBlock(&fs.body);
                    self.indent_level -= 1;
                    try self.writeIndent();
                    try self.writeStr("}\n");
                },
                .set => |s| {
                    // set is typedef'd to list — same iteration pattern
                    const elem_c = self.cTypeStringForId(s.element);
                    try self.writeIndent();
                    try self.writeFmt("for (int64_t {s} = 0; {s} < ", .{ idx_name, idx_name });
                    try self.emitExpr(fs.iterable);
                    try self.writeFmt(".len; {s}++) {{\n", .{idx_name});
                    self.indent_level += 1;
                    try self.writeIndent();
                    try self.writeStr(elem_c);
                    try self.writeFmt(" {s} = FORGE_LIST_GET(", .{fs.binding});
                    try self.emitExpr(fs.iterable);
                    try self.writeStr(", ");
                    try self.writeStr(elem_c);
                    try self.writeFmt(", {s});\n", .{idx_name});
                    self.local_types.put(fs.binding, s.element) catch {};
                    if (fs.index != null) self.local_types.put(idx_name, .int) catch {};
                    try self.emitBlock(&fs.body);
                    self.indent_level -= 1;
                    try self.writeIndent();
                    try self.writeStr("}\n");
                },
                else => {
                    try self.writeIndent();
                    try self.writeStr("/* for loop: unsupported iterable type */\n");
                },
            }
        } else {
            try self.writeIndent();
            try self.writeStr("/* for loop: could not resolve iterable type */\n");
        }
    }

    fn emitMatchStmt(self: *CEmitter, m: *const ast.MatchExpr) EmitError!void {
        // when a match statement is in a function that returns non-void,
        // the arms need `return` so the value gets returned to the caller.
        const needs_return = self.current_fn_return != .void;
        try self.emitMatchAsIfChain(m, true, needs_return);
    }

    // ---------------------------------------------------------------
    // expressions
    // ---------------------------------------------------------------

    fn emitExpr(self: *CEmitter, expr: *const ast.Expr) EmitError!void {
        switch (expr.kind) {
            .int_lit => |lit| try self.writeStr(lit),
            .float_lit => |lit| try self.writeStr(lit),
            .string_lit => |lit| try self.emitStringLit(lit),
            .bool_lit => |b| try self.writeStr(if (b) "true" else "false"),
            .none_lit => try self.writeStr("/* None */"),
            .ident => |name| try self.writeStr(name),
            .self_expr => try self.writeStr("self"),
            .binary => |bin| try self.emitBinary(&bin),
            .unary => |un| try self.emitUnary(&un),
            .call => |call| try self.emitCall(&call),
            .method_call => |mc| try self.emitMethodCall(&mc),
            .field_access => |fa| try self.emitFieldAccess(&fa),
            .index => |idx| try self.emitIndexExpr(&idx),
            .grouped => |inner| {
                try self.writeByte('(');
                try self.emitExpr(inner);
                try self.writeByte(')');
            },
            .if_expr => |if_e| try self.emitIfExpr(&if_e),
            .match_expr => |m| try self.emitMatchAsIfChain(&m, false, false),
            .string_interp => |interp| try self.emitStringInterp(&interp),
            .lambda => |_| try self.writeStr("/* lambda not yet supported */"),
            .list => |elems| try self.emitListLiteral(elems),
            .map => |entries| try self.emitMapLiteral(entries),
            .set => |elems| try self.emitSetLiteral(elems),
            .tuple => |_| try self.writeStr("/* tuple not yet supported */"),
            .unwrap => |_| try self.writeStr("/* unwrap not yet supported */"),
            .try_expr => |_| try self.writeStr("/* try not yet supported */"),
            .spawn_expr => |_| try self.writeStr("/* spawn not yet supported */"),
            .await_expr => |_| try self.writeStr("/* await not yet supported */"),
            .err => {},
        }
    }

    fn emitStringLit(self: *CEmitter, lit: []const u8) EmitError!void {
        // the lexer includes surrounding quotes in string literals — strip them
        const content = stripQuotes(lit);
        try self.writeStr("FORGE_STRING_LIT(\"");
        try self.writeEscapedString(content);
        try self.writeStr("\")");
    }

    /// strip surrounding double quotes if present. the lexer includes
    /// them in the lexeme for string literals.
    fn stripQuotes(s: []const u8) []const u8 {
        if (s.len >= 2 and s[0] == '"' and s[s.len - 1] == '"') {
            return s[1 .. s.len - 1];
        }
        return s;
    }

    fn emitBinary(self: *CEmitter, bin: *const ast.BinaryExpr) EmitError!void {
        // pipe operator: x |> f  →  fg_f(x)
        if (bin.op == .pipe) {
            // the right side should be a function name
            switch (bin.right.kind) {
                .ident => |name| try self.emitUserFnName(name),
                else => try self.emitExpr(bin.right),
            }
            try self.writeByte('(');
            try self.emitExpr(bin.left);
            try self.writeByte(')');
            return;
        }

        // string operations need special handling
        const is_string_op = self.isStringExpr(bin.left);

        if (is_string_op) {
            switch (bin.op) {
                .add => {
                    try self.writeStr("forge_string_concat(");
                    try self.emitExpr(bin.left);
                    try self.writeStr(", ");
                    try self.emitExpr(bin.right);
                    try self.writeByte(')');
                    return;
                },
                .eq => return self.emitStringCmp("forge_string_eq", bin),
                .neq => return self.emitStringCmp("forge_string_neq", bin),
                .lt => return self.emitStringCmp("forge_string_lt", bin),
                .gt => return self.emitStringCmp("forge_string_gt", bin),
                .lte => return self.emitStringCmp("forge_string_lte", bin),
                .gte => return self.emitStringCmp("forge_string_gte", bin),
                else => {},
            }
        }

        try self.writeByte('(');
        try self.emitExpr(bin.left);
        try self.writeStr(switch (bin.op) {
            .add => " + ",
            .sub => " - ",
            .mul => " * ",
            .div => " / ",
            .mod => " % ",
            .eq => " == ",
            .neq => " != ",
            .lt => " < ",
            .gt => " > ",
            .lte => " <= ",
            .gte => " >= ",
            .@"and" => " && ",
            .@"or" => " || ",
            .pipe => return, // handled above
        });
        try self.emitExpr(bin.right);
        try self.writeByte(')');
    }

    fn emitStringCmp(self: *CEmitter, func: []const u8, bin: *const ast.BinaryExpr) EmitError!void {
        try self.writeStr(func);
        try self.writeByte('(');
        try self.emitExpr(bin.left);
        try self.writeStr(", ");
        try self.emitExpr(bin.right);
        try self.writeByte(')');
    }

    /// is this expression a string? checks literal types, variable types,
    /// and function return types via the module scope.
    fn isStringExpr(self: *const CEmitter, expr: *const ast.Expr) bool {
        return self.inferExprType(expr) == .string;
    }

    fn emitUnary(self: *CEmitter, un: *const ast.UnaryExpr) EmitError!void {
        switch (un.op) {
            .negate => {
                try self.writeStr("(-");
                try self.emitExpr(un.operand);
                try self.writeByte(')');
            },
            .not => {
                try self.writeStr("(!");
                try self.emitExpr(un.operand);
                try self.writeByte(')');
            },
        }
    }

    fn emitCall(self: *CEmitter, call: *const ast.CallExpr) EmitError!void {
        const name = switch (call.callee.kind) {
            .ident => |n| n,
            else => {
                // indirect calls — emit as-is
                try self.emitExpr(call.callee);
                try self.emitArgList(call.args);
                return;
            },
        };

        // print() → forge_print()
        if (std.mem.eql(u8, name, "print")) {
            try self.writeStr("forge_print(");
            if (call.args.len > 0) {
                try self.emitExpr(call.args[0].value);
            }
            try self.writeByte(')');
            return;
        }

        // struct constructor: Name(args) → (Name){ .field1 = arg1, ... }
        if (self.type_table.lookup(name)) |tid| {
            if (self.type_table.get(tid)) |ty| {
                switch (ty) {
                    .@"struct" => |s| {
                        try self.writeByte('(');
                        try self.writeStr(name);
                        try self.writeStr("){ ");
                        for (s.fields, 0..) |field, i| {
                            if (i > 0) try self.writeStr(", ");
                            try self.writeByte('.');
                            try self.writeStr(field.name);
                            try self.writeStr(" = ");
                            if (i < call.args.len) {
                                try self.emitExpr(call.args[i].value);
                            }
                        }
                        try self.writeStr(" }");
                        return;
                    },
                    else => {},
                }
            }
        }

        // regular function call — prefixed to avoid C stdlib collisions
        try self.emitUserFnName(name);
        try self.emitArgList(call.args);
    }

    fn emitMethodCall(self: *CEmitter, mc: *const ast.MethodCallExpr) EmitError!void {
        // check for built-in collection methods first
        const receiver_tid = self.inferExprType(mc.receiver);
        if (!receiver_tid.isErr()) {
            if (self.type_table.get(receiver_tid)) |ty| {
                switch (ty) {
                    .list => |l| {
                        if (std.mem.eql(u8, mc.method, "push") and mc.args.len == 1) {
                            return self.emitCollectionPush(mc.receiver, mc.args[0].value, l.element);
                        }
                    },
                    .map => |m| {
                        if (std.mem.eql(u8, mc.method, "insert") and mc.args.len == 2) {
                            return self.emitMapInsert(mc.receiver, mc.args[0].value, mc.args[1].value, m.key, m.value);
                        }
                    },
                    .set => |s| {
                        if (std.mem.eql(u8, mc.method, "add") and mc.args.len == 1) {
                            return self.emitSetAdd(mc.receiver, mc.args[0].value, s.element);
                        }
                    },
                    else => {},
                }
            }
        }

        // user-defined methods: TypeName_methodname(receiver, args...)
        const type_name = self.typeNameFromId(receiver_tid);

        if (type_name) |name| {
            try self.writeStr(name);
            try self.writeByte('_');
            try self.writeStr(mc.method);
            try self.writeByte('(');
            try self.emitExpr(mc.receiver);
            for (mc.args) |arg| {
                try self.writeStr(", ");
                try self.emitExpr(arg.value);
            }
            try self.writeByte(')');
        } else {
            // fallback — can't resolve receiver type
            try self.writeStr("/* method call: ");
            try self.writeStr(mc.method);
            try self.writeStr(" */");
        }
    }

    /// emit forge_list_push(&list, &(T){value}, sizeof(T))
    fn emitCollectionPush(self: *CEmitter, receiver: *const ast.Expr, value: *const ast.Expr, elem_type: TypeId) EmitError!void {
        const c_type = self.cTypeStringForId(elem_type);
        try self.writeStr("forge_list_push(&");
        try self.emitExpr(receiver);
        try self.writeStr(", &(");
        try self.writeStr(c_type);
        try self.writeStr("){");
        try self.emitExpr(value);
        try self.writeStr("}, sizeof(");
        try self.writeStr(c_type);
        try self.writeStr("))");
    }

    /// emit forge_map_set_by_{string,int}(&map, key, &(V){val}, sizeof(K), sizeof(V))
    fn emitMapInsert(self: *CEmitter, receiver: *const ast.Expr, key: *const ast.Expr, value: *const ast.Expr, key_type: TypeId, val_type: TypeId) EmitError!void {
        const key_c = self.cTypeStringForId(key_type);
        const val_c = self.cTypeStringForId(val_type);
        if (key_type == .string) {
            try self.writeStr("forge_map_set_by_string(&");
        } else {
            try self.writeStr("forge_map_set_by_int(&");
        }
        try self.emitExpr(receiver);
        try self.writeStr(", ");
        try self.emitExpr(key);
        try self.writeStr(", &(");
        try self.writeStr(val_c);
        try self.writeStr("){");
        try self.emitExpr(value);
        try self.writeStr("}, sizeof(");
        try self.writeStr(key_c);
        try self.writeStr("), sizeof(");
        try self.writeStr(val_c);
        try self.writeStr("))");
    }

    /// emit forge_set_add(&set, &(T){value}, sizeof(T))
    fn emitSetAdd(self: *CEmitter, receiver: *const ast.Expr, value: *const ast.Expr, elem_type: TypeId) EmitError!void {
        const c_type = self.cTypeStringForId(elem_type);
        try self.writeStr("forge_set_add(&");
        try self.emitExpr(receiver);
        try self.writeStr(", &(");
        try self.writeStr(c_type);
        try self.writeStr("){");
        try self.emitExpr(value);
        try self.writeStr("}, sizeof(");
        try self.writeStr(c_type);
        try self.writeStr("))");
    }

    /// get the type name string for a TypeId by looking it up in the type table.
    fn typeNameFromId(self: *const CEmitter, tid: TypeId) ?[]const u8 {
        if (tid.isErr()) return null;
        const ty = self.type_table.get(tid) orelse return null;
        return switch (ty) {
            .@"struct" => |s| s.name,
            .@"enum" => |e| e.name,
            else => null,
        };
    }

    /// look up a method's function type id from the checker's method_types.
    /// key format is "TypeName.methodName".
    fn lookupMethodKey(self: *const CEmitter, type_name: []const u8, method_name: []const u8) ?TypeId {
        // build the key in a stack buffer to avoid allocation
        var buf: [256]u8 = undefined;
        const key = std.fmt.bufPrint(&buf, "{s}.{s}", .{ type_name, method_name }) catch return null;
        const entry = self.method_types.get(key) orelse return null;
        return entry.type_id;
    }

    fn emitFieldAccess(self: *CEmitter, fa: *const ast.FieldAccess) EmitError!void {
        try self.emitExpr(fa.object);
        try self.writeByte('.');
        try self.writeStr(fa.field);
    }

    // ---------------------------------------------------------------
    // collection literals
    // ---------------------------------------------------------------

    fn emitListLiteral(self: *CEmitter, elems: []const *const ast.Expr) EmitError!void {
        if (elems.len == 0) {
            try self.writeStr("forge_list_create(0, 0, NULL)");
            return;
        }
        const elem_tid = self.inferExprType(elems[0]);
        const c_type = self.cTypeStringForId(elem_tid);
        try self.writeFmt("forge_list_create({d}, sizeof(", .{@as(i64, @intCast(elems.len))});
        try self.writeStr(c_type);
        try self.writeStr("), (");
        try self.writeStr(c_type);
        try self.writeStr("[]){");
        for (elems, 0..) |elem, i| {
            if (i > 0) try self.writeStr(", ");
            try self.emitExpr(elem);
        }
        try self.writeStr("})");
    }

    fn emitMapLiteral(self: *CEmitter, entries: []const ast.MapEntry) EmitError!void {
        if (entries.len == 0) {
            try self.writeStr("(forge_map_t){.keys = NULL, .values = NULL, .len = 0}");
            return;
        }
        const key_tid = self.inferExprType(entries[0].key);
        const val_tid = self.inferExprType(entries[0].value);
        const key_c = self.cTypeStringForId(key_tid);
        const val_c = self.cTypeStringForId(val_tid);

        try self.writeFmt("forge_map_create({d}, sizeof(", .{@as(i64, @intCast(entries.len))});
        try self.writeStr(key_c);
        try self.writeStr("), sizeof(");
        try self.writeStr(val_c);
        try self.writeStr("), (");
        try self.writeStr(key_c);
        try self.writeStr("[]){");
        for (entries, 0..) |entry, i| {
            if (i > 0) try self.writeStr(", ");
            try self.emitExpr(entry.key);
        }
        try self.writeStr("}, (");
        try self.writeStr(val_c);
        try self.writeStr("[]){");
        for (entries, 0..) |entry, i| {
            if (i > 0) try self.writeStr(", ");
            try self.emitExpr(entry.value);
        }
        try self.writeStr("})");
    }

    fn emitSetLiteral(self: *CEmitter, elems: []const *const ast.Expr) EmitError!void {
        if (elems.len == 0) {
            try self.writeStr("forge_set_create(0, 0, NULL)");
            return;
        }
        const elem_tid = self.inferExprType(elems[0]);
        const c_type = self.cTypeStringForId(elem_tid);
        try self.writeFmt("forge_set_create({d}, sizeof(", .{@as(i64, @intCast(elems.len))});
        try self.writeStr(c_type);
        try self.writeStr("), (");
        try self.writeStr(c_type);
        try self.writeStr("[]){");
        for (elems, 0..) |elem, i| {
            if (i > 0) try self.writeStr(", ");
            try self.emitExpr(elem);
        }
        try self.writeStr("})");
    }

    fn emitIndexExpr(self: *CEmitter, idx: *const ast.IndexExpr) EmitError!void {
        const obj_tid = self.inferExprType(idx.object);
        if (self.type_table.get(obj_tid)) |ty| {
            switch (ty) {
                .list => |l| {
                    const elem_c = self.cTypeStringForId(l.element);
                    try self.writeStr("FORGE_LIST_GET(");
                    try self.emitExpr(idx.object);
                    try self.writeStr(", ");
                    try self.writeStr(elem_c);
                    try self.writeStr(", ");
                    try self.emitExpr(idx.index);
                    try self.writeByte(')');
                },
                .map => |m| {
                    const val_c = self.cTypeStringForId(m.value);
                    try self.writeStr("*(");
                    try self.writeStr(val_c);
                    try self.writeStr("*)forge_map_get_checked(");
                    // dispatch on key type
                    if (m.key == .string) {
                        try self.writeStr("forge_map_get_by_string(");
                    } else {
                        try self.writeStr("forge_map_get_by_int(");
                    }
                    try self.emitExpr(idx.object);
                    try self.writeStr(", ");
                    try self.emitExpr(idx.index);
                    try self.writeStr(", sizeof(");
                    try self.writeStr(val_c);
                    try self.writeStr(")))");
                },
                else => {
                    try self.writeStr("/* index on unsupported type */");
                },
            }
        } else {
            try self.writeStr("/* index: unknown obj type */");
        }
    }

    fn emitArgList(self: *CEmitter, args: []const ast.Arg) EmitError!void {
        try self.writeByte('(');
        for (args, 0..) |arg, i| {
            if (i > 0) try self.writeStr(", ");
            try self.emitExpr(arg.value);
        }
        try self.writeByte(')');
    }

    fn emitIfExpr(self: *CEmitter, if_e: *const ast.IfExpr) EmitError!void {
        // ternary: condition ? then : else
        // for elif chains, nest them
        try self.writeByte('(');
        try self.emitExpr(if_e.condition);
        try self.writeStr(" ? ");
        try self.emitExpr(if_e.then_expr);
        try self.writeStr(" : ");
        if (if_e.elif_branches.len > 0) {
            // nested ternaries for elif
            for (if_e.elif_branches) |*elif| {
                try self.emitExpr(elif.condition);
                try self.writeStr(" ? ");
                try self.emitExpr(elif.expr);
                try self.writeStr(" : ");
            }
        }
        try self.emitExpr(if_e.else_expr);
        try self.writeByte(')');
    }

    fn emitStringInterp(self: *CEmitter, interp: *const ast.StringInterp) EmitError!void {
        // string interpolation: "hello {name}!" → forge_string_concat chain
        const part_count = interp.parts.len;

        if (part_count == 0) {
            try self.writeStr("forge_string_empty");
            return;
        }
        if (part_count == 1) {
            try self.emitStringPart(&interp.parts[0]);
            return;
        }

        // nested concat calls: concat(concat(a, b), c)
        // for N parts we need N-1 concat calls, so N-2 leading opens
        // (the first concat wraps parts 0 and 1, each subsequent wraps
        // the previous result and the next part)
        var i: usize = 0;
        while (i + 2 < part_count) : (i += 1) {
            try self.writeStr("forge_string_concat(");
        }

        // emit first concat pair
        try self.writeStr("forge_string_concat(");
        try self.emitStringPart(&interp.parts[0]);
        try self.writeStr(", ");
        try self.emitStringPart(&interp.parts[1]);
        try self.writeByte(')');

        // emit remaining parts, each wrapped in a concat with the result so far
        for (interp.parts[2..]) |*part| {
            try self.writeStr(", ");
            try self.emitStringPart(part);
            try self.writeByte(')');
        }
    }

    fn emitStringPart(self: *CEmitter, part: *const ast.StringPart) EmitError!void {
        switch (part.*) {
            .literal => |lit| {
                // interpolation literal parts may include boundary quotes
                // from the lexer (string_start has leading ", string_end
                // has trailing "). strip them.
                var content = lit;
                if (content.len > 0 and content[0] == '"')
                    content = content[1..];
                if (content.len > 0 and content[content.len - 1] == '"')
                    content = content[0 .. content.len - 1];
                try self.writeStr("FORGE_STRING_LIT(\"");
                try self.writeEscapedString(content);
                try self.writeStr("\")");
            },
            .expr => |expr| {
                // need to convert the expression to string
                try self.emitExprAsString(expr);
            },
        }
    }

    /// emit an expression converted to forge_string_t. uses type inference
    /// to pick the right conversion function.
    fn emitExprAsString(self: *CEmitter, expr: *const ast.Expr) EmitError!void {
        const tid = self.inferExprType(expr);
        if (tid == .string) {
            // already a string — emit directly
            try self.emitExpr(expr);
            return;
        }
        if (tid == .int or tid.isInteger()) {
            try self.writeStr("forge_int_to_string(");
            try self.emitExpr(expr);
            try self.writeByte(')');
            return;
        }
        if (tid == .float) {
            try self.writeStr("forge_float_to_string(");
            try self.emitExpr(expr);
            try self.writeByte(')');
            return;
        }
        if (tid == .bool) {
            try self.writeStr("forge_bool_to_string(");
            try self.emitExpr(expr);
            try self.writeByte(')');
            return;
        }
        // fallback: use the expression kind for literals
        switch (expr.kind) {
            .string_lit => |lit| try self.emitStringLit(lit),
            .string_interp => |interp| try self.emitStringInterp(&interp),
            .int_lit => {
                try self.writeStr("forge_int_to_string(");
                try self.emitExpr(expr);
                try self.writeByte(')');
            },
            .float_lit => {
                try self.writeStr("forge_float_to_string(");
                try self.emitExpr(expr);
                try self.writeByte(')');
            },
            .bool_lit => {
                try self.writeStr("forge_bool_to_string(");
                try self.emitExpr(expr);
                try self.writeByte(')');
            },
            else => {
                // last resort — assume it's already a string expression
                try self.emitExpr(expr);
            },
        }
    }

    fn emitMatchAsIfChain(self: *CEmitter, m: *const ast.MatchExpr, is_stmt: bool, needs_return: bool) EmitError!void {
        if (m.arms.len == 0) return;

        if (is_stmt) {
            // open a scoped block
            try self.writeIndent();
            try self.writeStr("{\n");
            self.indent_level += 1;
        }

        for (m.arms, 0..) |*arm, i| {
            const is_last = i == m.arms.len - 1;
            const is_wildcard = arm.pattern.kind == .wildcard or arm.pattern.kind == .binding;

            if (is_stmt) {
                if (i == 0) {
                    if (is_wildcard and is_last) {
                        // single wildcard arm — just emit the body
                    } else if (!is_wildcard) {
                        try self.writeIndent();
                        try self.writeStr("if (");
                        try self.emitPatternCondition(m.subject, &arm.pattern);
                        try self.writeStr(") {\n");
                        self.indent_level += 1;
                    }
                } else if (is_wildcard and is_last) {
                    try self.writeIndent();
                    try self.writeStr("} else {\n");
                    self.indent_level += 1;
                } else {
                    try self.writeIndent();
                    try self.writeStr("} else if (");
                    try self.emitPatternCondition(m.subject, &arm.pattern);
                    try self.writeStr(") {\n");
                    self.indent_level += 1;
                }

                // emit binding if present — use subject's type
                if (arm.pattern.kind == .binding) {
                    const subject_type = self.inferExprType(m.subject);
                    try self.writeIndent();
                    if (!subject_type.isErr()) {
                        try self.emitCType(subject_type);
                    } else {
                        try self.emitTypeForExpr(m.subject);
                    }
                    try self.writeByte(' ');
                    try self.writeStr(arm.pattern.kind.binding);
                    try self.writeStr(" = ");
                    try self.emitExpr(m.subject);
                    try self.writeStr(";\n");
                }

                switch (arm.body) {
                    .expr => |e| {
                        try self.writeIndent();
                        if (needs_return) try self.writeStr("return ");
                        try self.emitExpr(e);
                        try self.writeStr(";\n");
                    },
                    .block => |*blk| try self.emitBlock(blk),
                }

                if (!is_wildcard or !is_last) {
                    self.indent_level -= 1;
                } else if (i > 0) {
                    self.indent_level -= 1;
                    try self.writeIndent();
                    try self.writeStr("}\n");
                }
            } else {
                // match as expression — emit as ternary chain
                if (i > 0) try self.writeStr(" : ");
                if (!is_wildcard or !is_last) {
                    try self.writeStr("(");
                    try self.emitPatternCondition(m.subject, &arm.pattern);
                    try self.writeStr(" ? ");
                }
                switch (arm.body) {
                    .expr => |e| try self.emitExpr(e),
                    .block => |*blk| {
                        // block arm in expression context — emit last statement
                        if (blk.stmts.len > 0) {
                            const last_stmt = blk.stmts[blk.stmts.len - 1];
                            switch (last_stmt.kind) {
                                .expr_stmt => |e| try self.emitExpr(e),
                                else => try self.writeStr("0 /* block */"),
                            }
                        } else {
                            try self.writeStr("0 /* empty block */");
                        }
                    },
                }
                if (!is_wildcard or !is_last) {
                    try self.writeByte(')');
                }
            }
        }

        if (is_stmt) {
            // close the last if block if needed
            if (m.arms.len > 0) {
                const last = m.arms[m.arms.len - 1];
                const last_is_wildcard = last.pattern.kind == .wildcard or last.pattern.kind == .binding;
                if (!last_is_wildcard) {
                    try self.writeIndent();
                    try self.writeStr("}\n");
                }
            }
            self.indent_level -= 1;
            try self.writeIndent();
            try self.writeStr("}\n");
        }
    }

    fn emitPatternCondition(self: *CEmitter, subject: *const ast.Expr, pattern: *const ast.Pattern) EmitError!void {
        switch (pattern.kind) {
            .wildcard, .binding => try self.writeStr("1"),
            .int_lit => |lit| {
                try self.emitExpr(subject);
                try self.writeStr(" == ");
                try self.writeStr(lit);
            },
            .float_lit => |lit| {
                try self.emitExpr(subject);
                try self.writeStr(" == ");
                try self.writeStr(lit);
            },
            .string_lit => |lit| {
                const content = stripQuotes(lit);
                try self.writeStr("forge_string_eq(");
                try self.emitExpr(subject);
                try self.writeStr(", FORGE_STRING_LIT(\"");
                try self.writeEscapedString(content);
                try self.writeStr("\"))");
            },
            .bool_lit => |b| {
                try self.emitExpr(subject);
                try self.writeStr(if (b) " == true" else " == false");
            },
            .none_lit => try self.writeStr("0 /* None pattern */"),
            .variant => |vp| {
                try self.emitExpr(subject);
                try self.writeStr(".tag == ");
                try self.writeStr(vp.type_name);
                try self.writeStr("_TAG_");
                try self.writeStr(vp.variant);
            },
            .tuple => |_| try self.writeStr("1 /* tuple pattern */"),
        }
    }

    // ---------------------------------------------------------------
    // type inference helpers
    // ---------------------------------------------------------------

    /// resolve the TypeId for an AST type expression. used to track
    /// parameter and binding types during emission.
    fn resolveTypeExprToId(self: *const CEmitter, te: *const ast.TypeExpr) TypeId {
        return switch (te.kind) {
            .named => |name| {
                if (std.mem.eql(u8, name, "Int")) return .int;
                if (std.mem.eql(u8, name, "UInt")) return .uint;
                if (std.mem.eql(u8, name, "Float")) return .float;
                if (std.mem.eql(u8, name, "Bool")) return .bool;
                if (std.mem.eql(u8, name, "String")) return .string;
                if (std.mem.eql(u8, name, "Void")) return .void;
                if (std.mem.eql(u8, name, "Bytes")) return .bytes;
                // user-defined — look up in the type table
                return self.type_table.lookup(name) orelse .err;
            },
            .generic => |g| {
                // build the instantiated name: "List[Int]", "Map[String,Int]"
                var buf: [128]u8 = undefined;
                var pos: usize = 0;
                for (g.name) |c| {
                    if (pos < buf.len) {
                        buf[pos] = c;
                        pos += 1;
                    }
                }
                if (pos < buf.len) {
                    buf[pos] = '[';
                    pos += 1;
                }
                for (g.args, 0..) |arg, i| {
                    if (i > 0 and pos < buf.len) {
                        buf[pos] = ',';
                        pos += 1;
                    }
                    const arg_name = switch (arg.kind) {
                        .named => |n| n,
                        else => continue,
                    };
                    for (arg_name) |c| {
                        if (pos < buf.len) {
                            buf[pos] = c;
                            pos += 1;
                        }
                    }
                }
                if (pos < buf.len) {
                    buf[pos] = ']';
                    pos += 1;
                }
                return self.type_table.lookup(buf[0..pos]) orelse .err;
            },
            else => .err,
        };
    }

    /// infer the TypeId of an expression. uses local variable types,
    /// module scope (for function return types), and expression structure.
    fn inferExprType(self: *const CEmitter, expr: *const ast.Expr) TypeId {
        return switch (expr.kind) {
            .int_lit => .int,
            .float_lit => .float,
            .string_lit, .string_interp => .string,
            .bool_lit => .bool,
            .none_lit => .void,
            .self_expr => {
                // `self` is registered as a local variable in method bodies
                if (self.local_types.get("self")) |tid| return tid;
                return .err;
            },
            .ident => |name| {
                // check local variables first
                if (self.local_types.get(name)) |tid| return tid;
                // then module scope (functions, etc.)
                if (self.module_scope.lookup(name)) |binding| {
                    return binding.type_id;
                }
                return .err;
            },
            .binary => |bin| {
                switch (bin.op) {
                    .eq, .neq, .lt, .gt, .lte, .gte, .@"and", .@"or" => return .bool,
                    .add => {
                        const left_type = self.inferExprType(bin.left);
                        if (left_type == .string) return .string;
                        return left_type;
                    },
                    .pipe => {
                        // x | f → result type is f's return type
                        const fn_name = switch (bin.right.kind) {
                            .ident => |n| n,
                            else => return self.inferExprType(bin.left),
                        };
                        if (self.module_scope.lookup(fn_name)) |binding| {
                            if (self.type_table.get(binding.type_id)) |ty| {
                                switch (ty) {
                                    .function => |f| return f.return_type,
                                    else => {},
                                }
                            }
                        }
                        return self.inferExprType(bin.left);
                    },
                    else => return self.inferExprType(bin.left),
                }
            },
            .unary => |un| {
                return switch (un.op) {
                    .not => .bool,
                    .negate => self.inferExprType(un.operand),
                };
            },
            .call => |call| {
                // look up the function's return type
                const name = switch (call.callee.kind) {
                    .ident => |n| n,
                    else => return .err,
                };
                // check module scope first (functions, builtins)
                if (self.module_scope.lookup(name)) |binding| {
                    if (self.type_table.get(binding.type_id)) |ty| {
                        switch (ty) {
                            .function => |f| return f.return_type,
                            .@"struct" => return binding.type_id,
                            else => {},
                        }
                    }
                }
                // check type table for struct/enum constructors
                if (self.type_table.lookup(name)) |tid| {
                    if (self.type_table.get(tid)) |ty| {
                        switch (ty) {
                            .@"struct", .@"enum" => return tid,
                            else => {},
                        }
                    }
                }
                return .err;
            },
            .method_call => |mc| {
                // resolve the receiver's type, then look up the method
                const receiver_tid = self.inferExprType(mc.receiver);
                const type_name = self.typeNameFromId(receiver_tid) orelse return .err;
                const key = self.lookupMethodKey(type_name, mc.method) orelse return .err;
                if (self.type_table.get(key)) |ty| {
                    switch (ty) {
                        .function => |f| return f.return_type,
                        else => {},
                    }
                }
                return .err;
            },
            .field_access => |fa| {
                // resolve the struct type and look up the field
                const obj_type = self.inferExprType(fa.object);
                if (self.type_table.get(obj_type)) |ty| {
                    switch (ty) {
                        .@"struct" => |s| {
                            for (s.fields) |field| {
                                if (std.mem.eql(u8, field.name, fa.field))
                                    return field.type_id;
                            }
                        },
                        else => {},
                    }
                }
                return .err;
            },
            .grouped => |inner| return self.inferExprType(inner),
            .if_expr => |if_e| return self.inferExprType(if_e.then_expr),
            .list => |elems| {
                if (elems.len == 0) return .err;
                const elem_tid = self.inferExprType(elems[0]);
                const elem_name = self.type_table.typeName(elem_tid);
                // look up "List[ElemType]" in the type table
                var buf: [128]u8 = undefined;
                const inst = std.fmt.bufPrint(&buf, "List[{s}]", .{elem_name}) catch return .err;
                return self.type_table.lookup(inst) orelse .err;
            },
            .map => |entries| {
                if (entries.len == 0) return .err;
                const key_tid = self.inferExprType(entries[0].key);
                const val_tid = self.inferExprType(entries[0].value);
                const key_name = self.type_table.typeName(key_tid);
                const val_name = self.type_table.typeName(val_tid);
                var buf: [128]u8 = undefined;
                const inst = std.fmt.bufPrint(&buf, "Map[{s},{s}]", .{ key_name, val_name }) catch return .err;
                return self.type_table.lookup(inst) orelse .err;
            },
            .set => |elems| {
                if (elems.len == 0) return .err;
                const elem_tid = self.inferExprType(elems[0]);
                const elem_name = self.type_table.typeName(elem_tid);
                var buf: [128]u8 = undefined;
                const inst = std.fmt.bufPrint(&buf, "Set[{s}]", .{elem_name}) catch return .err;
                return self.type_table.lookup(inst) orelse .err;
            },
            .index => |idx| {
                const obj_tid = self.inferExprType(idx.object);
                if (self.type_table.get(obj_tid)) |ty| {
                    return switch (ty) {
                        .list => |l| l.element,
                        .map => |m| m.value,
                        else => .err,
                    };
                }
                return .err;
            },
            else => .err,
        };
    }

    // ---------------------------------------------------------------
    // type emission
    // ---------------------------------------------------------------

    fn emitTypeExpr(self: *CEmitter, te: *const ast.TypeExpr) EmitError!void {
        switch (te.kind) {
            .named => |name| try self.emitNamedType(name),
            .generic => |g| {
                // collection types map to runtime C types
                if (std.mem.eql(u8, g.name, "List")) {
                    try self.writeStr("forge_list_t");
                } else if (std.mem.eql(u8, g.name, "Map")) {
                    try self.writeStr("forge_map_t");
                } else if (std.mem.eql(u8, g.name, "Set")) {
                    try self.writeStr("forge_set_t");
                } else {
                    try self.writeStr(g.name);
                }
            },
            .optional => try self.writeStr("/* optional */"),
            .result => try self.writeStr("/* result */"),
            .tuple => try self.writeStr("/* tuple type */"),
            .fn_type => try self.writeStr("/* fn type */"),
        }
    }

    fn emitNamedType(self: *CEmitter, name: []const u8) EmitError!void {
        try self.writeStr(mapType(name));
    }

    /// emit a C type for a TypeId from the type table.
    pub fn emitCType(self: *CEmitter, tid: TypeId) EmitError!void {
        try self.writeStr(mapTypeId(tid));

        // user-defined types — look up the name
        if (tid.index() >= TypeId.first_user) {
            if (self.type_table.get(tid)) |ty| {
                switch (ty) {
                    .@"struct" => |s| {
                        try self.writeStr(s.name);
                        return;
                    },
                    .@"enum" => |e| {
                        try self.writeStr(e.name);
                        return;
                    },
                    .list => {
                        try self.writeStr("forge_list_t");
                        return;
                    },
                    .map => {
                        try self.writeStr("forge_map_t");
                        return;
                    },
                    .set => {
                        try self.writeStr("forge_set_t");
                        return;
                    },
                    else => {},
                }
            }
        }
    }

    // ---------------------------------------------------------------
    // type mapping
    // ---------------------------------------------------------------

    /// map a forge type name to a C type string.
    pub fn mapType(name: []const u8) []const u8 {
        if (std.mem.eql(u8, name, "Int")) return "int64_t";
        if (std.mem.eql(u8, name, "UInt")) return "uint64_t";
        if (std.mem.eql(u8, name, "Float")) return "double";
        if (std.mem.eql(u8, name, "Bool")) return "bool";
        if (std.mem.eql(u8, name, "String")) return "forge_string_t";
        if (std.mem.eql(u8, name, "Bytes")) return "uint8_t*";
        if (std.mem.eql(u8, name, "Void")) return "void";
        if (std.mem.eql(u8, name, "Int8")) return "int8_t";
        if (std.mem.eql(u8, name, "Int16")) return "int16_t";
        if (std.mem.eql(u8, name, "Int32")) return "int32_t";
        if (std.mem.eql(u8, name, "Int64")) return "int64_t";
        if (std.mem.eql(u8, name, "UInt8")) return "uint8_t";
        if (std.mem.eql(u8, name, "UInt16")) return "uint16_t";
        if (std.mem.eql(u8, name, "UInt32")) return "uint32_t";
        if (std.mem.eql(u8, name, "UInt64")) return "uint64_t";
        // user-defined type — use the name as-is (should be typedef'd)
        return name;
    }

    /// map a TypeId to a C type string for builtin types.
    /// returns empty string for user-defined types (caller handles those).
    pub fn mapTypeId(tid: TypeId) []const u8 {
        return switch (tid) {
            .int => "int64_t",
            .uint => "uint64_t",
            .float => "double",
            .bool => "bool",
            .string => "forge_string_t",
            .bytes => "uint8_t*",
            .void => "void",
            .int8 => "int8_t",
            .int16 => "int16_t",
            .int32 => "int32_t",
            .int64 => "int64_t",
            .uint8 => "uint8_t",
            .uint16 => "uint16_t",
            .uint32 => "uint32_t",
            .uint64 => "uint64_t",
            .err => "/* error */",
            _ => "", // user-defined — caller handles
        };
    }

    /// return the C type string for any TypeId — builtins and user-defined.
    /// for collection types returns the runtime struct name; for structs/enums
    /// returns the forge type name (which is typedef'd in emitted C).
    fn cTypeStringForId(self: *CEmitter, tid: TypeId) []const u8 {
        // builtins have a direct mapping
        const builtin = mapTypeId(tid);
        if (builtin.len > 0) return builtin;

        // user-defined — look up in the type table
        if (self.type_table.get(tid)) |ty| {
            return switch (ty) {
                .@"struct" => |s| s.name,
                .@"enum" => |e| e.name,
                .list => "forge_list_t",
                .map => "forge_map_t",
                .set => "forge_set_t",
                else => "/* unknown */",
            };
        }
        return "/* unknown */";
    }

    // ---------------------------------------------------------------
    // output helpers
    // ---------------------------------------------------------------

    fn writeStr(self: *CEmitter, s: []const u8) EmitError!void {
        try self.output.appendSlice(self.allocator, s);
    }

    fn writeByte(self: *CEmitter, b: u8) EmitError!void {
        try self.output.append(self.allocator, b);
    }

    fn writeFmt(self: *CEmitter, comptime fmt: []const u8, args: anytype) EmitError!void {
        var buf: [256]u8 = undefined;
        const s = std.fmt.bufPrint(&buf, fmt, args) catch return;
        try self.output.appendSlice(self.allocator, s);
    }

    fn writeIndent(self: *CEmitter) EmitError!void {
        var i: u32 = 0;
        while (i < self.indent_level) : (i += 1) {
            try self.output.appendSlice(self.allocator, "    ");
        }
    }

    fn writeEscapedString(self: *CEmitter, s: []const u8) EmitError!void {
        for (s) |c| {
            switch (c) {
                '\\' => try self.output.appendSlice(self.allocator, "\\\\"),
                '"' => try self.output.appendSlice(self.allocator, "\\\""),
                '\n' => try self.output.appendSlice(self.allocator, "\\n"),
                '\r' => try self.output.appendSlice(self.allocator, "\\r"),
                '\t' => try self.output.appendSlice(self.allocator, "\\t"),
                else => try self.output.append(self.allocator, c),
            }
        }
    }
};

// ---------------------------------------------------------------
// tests
// ---------------------------------------------------------------

test "mapType maps forge primitives to C types" {
    try std.testing.expectEqualStrings("int64_t", CEmitter.mapType("Int"));
    try std.testing.expectEqualStrings("uint64_t", CEmitter.mapType("UInt"));
    try std.testing.expectEqualStrings("double", CEmitter.mapType("Float"));
    try std.testing.expectEqualStrings("bool", CEmitter.mapType("Bool"));
    try std.testing.expectEqualStrings("forge_string_t", CEmitter.mapType("String"));
    try std.testing.expectEqualStrings("void", CEmitter.mapType("Void"));
    try std.testing.expectEqualStrings("int8_t", CEmitter.mapType("Int8"));
    try std.testing.expectEqualStrings("uint64_t", CEmitter.mapType("UInt64"));
}

test "mapType passes through user-defined types" {
    try std.testing.expectEqualStrings("Point", CEmitter.mapType("Point"));
    try std.testing.expectEqualStrings("MyStruct", CEmitter.mapType("MyStruct"));
}

test "mapTypeId maps builtin type ids" {
    try std.testing.expectEqualStrings("int64_t", CEmitter.mapTypeId(.int));
    try std.testing.expectEqualStrings("double", CEmitter.mapTypeId(.float));
    try std.testing.expectEqualStrings("bool", CEmitter.mapTypeId(.bool));
    try std.testing.expectEqualStrings("forge_string_t", CEmitter.mapTypeId(.string));
    try std.testing.expectEqualStrings("void", CEmitter.mapTypeId(.void));
}

test "mapTypeId returns empty for user-defined types" {
    const user_id = TypeId.fromIndex(TypeId.first_user);
    try std.testing.expectEqualStrings("", CEmitter.mapTypeId(user_id));
}

test "emitter init and deinit" {
    var table = try TypeTable.init(std.testing.allocator);
    defer table.deinit();

    var scope = Scope.init(std.testing.allocator, null);
    defer scope.deinit();

    var methods = std.StringHashMap(Checker.MethodEntry).init(std.testing.allocator);
    defer methods.deinit();

    var emitter = CEmitter.init(std.testing.allocator, &table, &scope, &methods);
    defer emitter.deinit();

    try std.testing.expectEqual(@as(usize, 0), emitter.getOutput().len);
}

test "emitPreamble writes includes" {
    var table = try TypeTable.init(std.testing.allocator);
    defer table.deinit();

    var scope = Scope.init(std.testing.allocator, null);
    defer scope.deinit();

    var methods = std.StringHashMap(Checker.MethodEntry).init(std.testing.allocator);
    defer methods.deinit();

    var emitter = CEmitter.init(std.testing.allocator, &table, &scope, &methods);
    defer emitter.deinit();

    try emitter.emitPreamble();
    const output = emitter.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "forge_runtime.h") != null);
}

test "stripQuotes strips surrounding double quotes" {
    try std.testing.expectEqualStrings("hello", CEmitter.stripQuotes("\"hello\""));
    try std.testing.expectEqualStrings("", CEmitter.stripQuotes("\"\""));
    try std.testing.expectEqualStrings("no quotes", CEmitter.stripQuotes("no quotes"));
    try std.testing.expectEqualStrings("a", CEmitter.stripQuotes("a"));
}

test "full pipeline emits valid C for simple program" {
    const allocator = std.testing.allocator;
    const Lexer = @import("lexer.zig").Lexer;
    const Parser = @import("parser.zig").Parser;

    const source =
        \\fn main():
        \\    x := 42
        \\    print("hello")
        \\
    ;

    // lex
    var lexer = try Lexer.init(source, allocator);
    defer lexer.deinit();
    const tokens = try lexer.tokenize();
    defer allocator.free(tokens);

    // parse
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var parser = Parser.init(tokens, source, arena.allocator());
    defer parser.deinit();
    const module = try parser.parseModule();

    // check
    var checker = try Checker.Checker.init(allocator, source);
    defer checker.deinit();
    checker.check(&module);
    try std.testing.expect(!checker.diagnostics.hasErrors());

    // emit
    var emitter = CEmitter.init(allocator, &checker.type_table, &checker.module_scope, &checker.method_types);
    defer emitter.deinit();
    try emitter.emitModule(&module);

    const output = emitter.getOutput();

    // verify key elements in the output
    try std.testing.expect(std.mem.indexOf(u8, output, "int main(void)") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "int64_t x = 42") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "forge_print(FORGE_STRING_LIT(\"hello\"))") != null);
    try std.testing.expect(std.mem.indexOf(u8, output, "return 0;") != null);
}
