// codegen — C transpilation backend
//
// walks the type-checked AST and emits C source code. the generated C
// is compiled by `zig cc` to produce a native binary.
//
// the emitter does a single pass over the module:
//   1. emit #include and forward declarations
//   2. emit struct/enum type definitions
//   3. emit function definitions
//
// type mapping:
//   Int    → int64_t        Float  → double
//   Bool   → bool           String → forge_string_t
//   Void   → void           sized ints → stdint types
//
// the emitter assumes the AST has been type-checked. it uses the type
// table from the checker to resolve types for expressions, struct
// fields, etc.

const std = @import("std");
const ast = @import("ast.zig");
const types = @import("types.zig");

const TypeId = types.TypeId;
const TypeTable = types.TypeTable;
const Type = types.Type;

// ---------------------------------------------------------------
// C emitter
// ---------------------------------------------------------------

pub const CEmitter = struct {
    output: std.ArrayList(u8),
    indent_level: u32,
    type_table: *const TypeTable,
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator, type_table: *const TypeTable) CEmitter {
        return .{
            .output = .empty,
            .indent_level = 0,
            .type_table = type_table,
            .allocator = allocator,
        };
    }

    pub fn deinit(self: *CEmitter) void {
        self.output.deinit(self.allocator);
    }

    /// get the generated C source as a string slice.
    pub fn getOutput(self: *const CEmitter) []const u8 {
        return self.output.items;
    }

    // ---------------------------------------------------------------
    // module emission
    // ---------------------------------------------------------------

    /// emit a complete C translation unit from a forge module.
    pub fn emitModule(self: *CEmitter, module: *const ast.Module) !void {
        try self.emitPreamble();

        // pass 1: forward-declare all functions
        for (module.decls) |*decl| {
            switch (decl.kind) {
                .fn_decl => |*fd| try self.emitFnForwardDecl(fd),
                else => {},
            }
        }
        try self.writeByte('\n');

        // pass 2: struct type definitions
        for (module.decls) |*decl| {
            switch (decl.kind) {
                .struct_decl => |*sd| try self.emitStructDef(sd),
                else => {},
            }
        }

        // pass 3: enum type definitions
        for (module.decls) |*decl| {
            switch (decl.kind) {
                .enum_decl => |*ed| try self.emitEnumDef(ed),
                else => {},
            }
        }

        // pass 4: function definitions
        for (module.decls) |*decl| {
            switch (decl.kind) {
                .fn_decl => |*fd| try self.emitFnDef(fd),
                else => {},
            }
        }
    }

    fn emitPreamble(self: *CEmitter) !void {
        try self.writeStr("// generated by forge compiler — do not edit\n");
        try self.writeStr("#include \"forge_runtime.h\"\n\n");
    }

    // ---------------------------------------------------------------
    // struct definitions
    // ---------------------------------------------------------------

    fn emitStructDef(self: *CEmitter, sd: *const ast.StructDecl) !void {
        // skip generic (uninstantiated) structs
        if (sd.generic_params.len > 0) return;

        try self.writeStr("typedef struct {\n");
        self.indent_level += 1;
        for (sd.fields) |field| {
            try self.writeIndent();
            try self.emitCType(self.resolveFieldType(sd.name, field.name));
            try self.writeByte(' ');
            try self.writeStr(field.name);
            try self.writeStr(";\n");
        }
        self.indent_level -= 1;
        try self.writeStr("} ");
        try self.writeStr(sd.name);
        try self.writeStr(";\n\n");
    }

    /// look up the type of a struct field from the type table.
    fn resolveFieldType(self: *const CEmitter, struct_name: []const u8, field_name: []const u8) TypeId {
        const type_id = self.type_table.lookup(struct_name) orelse return .err;
        const ty = self.type_table.get(type_id) orelse return .err;
        const fields = switch (ty) {
            .@"struct" => |s| s.fields,
            else => return .err,
        };
        for (fields) |field| {
            if (std.mem.eql(u8, field.name, field_name)) return field.type_id;
        }
        return .err;
    }

    // ---------------------------------------------------------------
    // enum definitions
    // ---------------------------------------------------------------

    fn emitEnumDef(self: *CEmitter, ed: *const ast.EnumDecl) !void {
        // skip generic (uninstantiated) enums
        if (ed.generic_params.len > 0) return;

        // tag enum
        try self.writeStr("typedef enum {\n");
        self.indent_level += 1;
        for (ed.variants) |variant| {
            try self.writeIndent();
            try self.writeStr(ed.name);
            try self.writeStr("_TAG_");
            try self.writeStr(variant.name);
            try self.writeStr(",\n");
        }
        self.indent_level -= 1;
        try self.writeStr("} ");
        try self.writeStr(ed.name);
        try self.writeStr("_Tag;\n\n");

        // tagged union struct
        try self.writeStr("typedef struct {\n");
        self.indent_level += 1;
        try self.writeIndent();
        try self.writeStr(ed.name);
        try self.writeStr("_Tag tag;\n");

        // union of variant data (only if any variant has fields)
        var has_data = false;
        for (ed.variants) |variant| {
            if (variant.fields.len > 0) {
                has_data = true;
                break;
            }
        }

        if (has_data) {
            try self.writeIndent();
            try self.writeStr("union {\n");
            self.indent_level += 1;
            for (ed.variants) |variant| {
                if (variant.fields.len > 0) {
                    try self.writeIndent();
                    try self.writeStr("struct {\n");
                    self.indent_level += 1;
                    for (variant.fields, 0..) |_, i| {
                        try self.writeIndent();
                        const field_tid = self.resolveEnumFieldType(ed.name, variant.name, i);
                        try self.emitCType(field_tid);
                        try self.writeFmt(" _{d};\n", .{i});
                    }
                    self.indent_level -= 1;
                    try self.writeIndent();
                    try self.writeStr("} ");
                    try self.writeStr(variant.name);
                    try self.writeStr(";\n");
                }
            }
            self.indent_level -= 1;
            try self.writeIndent();
            try self.writeStr("} data;\n");
        }

        self.indent_level -= 1;
        try self.writeStr("} ");
        try self.writeStr(ed.name);
        try self.writeStr(";\n\n");
    }

    /// resolve the type of an enum variant field from the type table.
    fn resolveEnumFieldType(self: *const CEmitter, enum_name: []const u8, variant_name: []const u8, field_idx: usize) TypeId {
        const type_id = self.type_table.lookup(enum_name) orelse return .err;
        const ty = self.type_table.get(type_id) orelse return .err;
        const variants = switch (ty) {
            .@"enum" => |e| e.variants,
            else => return .err,
        };
        for (variants) |variant| {
            if (std.mem.eql(u8, variant.name, variant_name)) {
                if (field_idx < variant.fields.len) return variant.fields[field_idx];
                return .err;
            }
        }
        return .err;
    }

    // ---------------------------------------------------------------
    // function declarations
    // ---------------------------------------------------------------

    fn emitFnForwardDecl(self: *CEmitter, fd: *const ast.FnDecl) !void {
        // skip generic (uninstantiated) functions
        if (fd.generic_params.len > 0) return;

        // main is special — we emit it as int main(void)
        if (std.mem.eql(u8, fd.name, "main")) {
            try self.writeStr("int main(void);\n");
            return;
        }

        try self.emitReturnType(fd.return_type);
        try self.writeByte(' ');
        try self.writeStr(fd.name);
        try self.emitParamList(fd.params);
        try self.writeStr(";\n");
    }

    fn emitFnDef(self: *CEmitter, fd: *const ast.FnDecl) !void {
        // skip generic functions
        if (fd.generic_params.len > 0) return;

        if (std.mem.eql(u8, fd.name, "main")) {
            try self.writeStr("int main(void) {\n");
        } else {
            try self.emitReturnType(fd.return_type);
            try self.writeByte(' ');
            try self.writeStr(fd.name);
            try self.emitParamList(fd.params);
            try self.writeStr(" {\n");
        }

        self.indent_level += 1;
        try self.emitBlock(&fd.body);

        // if main, add return 0
        if (std.mem.eql(u8, fd.name, "main")) {
            try self.writeIndent();
            try self.writeStr("return 0;\n");
        }

        self.indent_level -= 1;
        try self.writeStr("}\n\n");
    }

    fn emitReturnType(self: *CEmitter, return_type: ?*const ast.TypeExpr) !void {
        if (return_type) |rt| {
            try self.emitTypeExpr(rt);
        } else {
            try self.writeStr("void");
        }
    }

    fn emitParamList(self: *CEmitter, params: []const ast.Param) !void {
        try self.writeByte('(');
        if (params.len == 0) {
            try self.writeStr("void");
        } else {
            for (params, 0..) |param, i| {
                if (i > 0) try self.writeStr(", ");
                if (param.type_expr) |te| {
                    try self.emitTypeExpr(te);
                } else {
                    try self.writeStr("/* unknown */");
                }
                try self.writeByte(' ');
                try self.writeStr(param.name);
            }
        }
        try self.writeByte(')');
    }

    // ---------------------------------------------------------------
    // block and statements
    // ---------------------------------------------------------------

    fn emitBlock(self: *CEmitter, block: *const ast.Block) !void {
        for (block.stmts) |*stmt| {
            try self.emitStmt(stmt);
        }
    }

    fn emitStmt(self: *CEmitter, stmt: *const ast.Stmt) !void {
        switch (stmt.kind) {
            .binding => |b| try self.emitBinding(&b),
            .assignment => |a| try self.emitAssignment(&a),
            .if_stmt => |ifs| try self.emitIfStmt(&ifs),
            .while_stmt => |ws| try self.emitWhileStmt(&ws),
            .return_stmt => |rs| try self.emitReturnStmt(&rs),
            .break_stmt => {
                try self.writeIndent();
                try self.writeStr("break;\n");
            },
            .continue_stmt => {
                try self.writeIndent();
                try self.writeStr("continue;\n");
            },
            .expr_stmt => |expr| {
                try self.writeIndent();
                try self.emitExpr(expr);
                try self.writeStr(";\n");
            },
            .match_stmt => |m| try self.emitMatchStmt(&m),
            .for_stmt => |fs| try self.emitForStmt(&fs),
            .fail_stmt => |_| {
                // fail not yet supported in codegen
                try self.writeIndent();
                try self.writeStr("/* fail not yet supported */\n");
            },
        }
    }

    fn emitBinding(self: *CEmitter, b: *const ast.Binding) !void {
        try self.writeIndent();
        if (b.type_expr) |te| {
            try self.emitTypeExpr(te);
        } else {
            // infer type from value — use the AST expression to guess
            try self.emitInferredType(b.value);
        }
        try self.writeByte(' ');
        try self.writeStr(b.name);
        try self.writeStr(" = ");
        try self.emitExpr(b.value);
        try self.writeStr(";\n");
    }

    /// emit a C type for a binding whose type annotation is omitted.
    /// we look at the expression to figure out the C type. this is a
    /// best-effort approach — the checker has already validated types.
    fn emitInferredType(self: *CEmitter, expr: *const ast.Expr) !void {
        switch (expr.kind) {
            .int_lit => try self.writeStr("int64_t"),
            .float_lit => try self.writeStr("double"),
            .string_lit, .string_interp => try self.writeStr("forge_string_t"),
            .bool_lit => try self.writeStr("bool"),
            .binary => |bin| {
                // comparison and logical ops produce bool
                switch (bin.op) {
                    .eq, .neq, .lt, .gt, .lte, .gte, .@"and", .@"or" => try self.writeStr("bool"),
                    .add => {
                        // could be string concat or numeric — check left operand
                        if (bin.left.kind == .string_lit or bin.left.kind == .string_interp) {
                            try self.writeStr("forge_string_t");
                        } else {
                            try self.emitInferredType(bin.left);
                        }
                    },
                    else => try self.emitInferredType(bin.left),
                }
            },
            .unary => |un| {
                switch (un.op) {
                    .not => try self.writeStr("bool"),
                    .negate => try self.emitInferredType(un.operand),
                }
            },
            .call => |call| {
                // struct constructor or function call — try to resolve
                switch (call.callee.kind) {
                    .ident => |name| {
                        // check if it's a known struct type
                        if (self.type_table.lookup(name)) |tid| {
                            if (self.type_table.get(tid)) |ty| {
                                if (ty == .@"struct") {
                                    try self.writeStr(name);
                                    return;
                                }
                                if (ty == .@"enum") {
                                    try self.writeStr(name);
                                    return;
                                }
                            }
                        }
                        // function call — look up return type
                        try self.emitFnReturnType(name);
                    },
                    else => try self.writeStr("/* unknown */"),
                }
            },
            .method_call => |_| {
                // method calls are harder to infer — emit a placeholder
                try self.writeStr("/* method_result */");
            },
            .field_access => |_| {
                try self.writeStr("/* field_type */");
            },
            .grouped => |inner| try self.emitInferredType(inner),
            .if_expr => |if_e| try self.emitInferredType(if_e.then_expr),
            .match_expr => |m| {
                if (m.arms.len > 0) {
                    switch (m.arms[0].body) {
                        .expr => |e| try self.emitInferredType(e),
                        .block => try self.writeStr("/* block_result */"),
                    }
                } else {
                    try self.writeStr("/* empty match */");
                }
            },
            else => try self.writeStr("/* unknown */"),
        }
    }

    /// look up a function's return type from the type table (by name in module scope).
    fn emitFnReturnType(self: *CEmitter, name: []const u8) !void {
        // this is a best-effort lookup — we don't have the scope here,
        // but the type table has all registered function types
        // for now, use a conservative fallback
        _ = name;
        try self.writeStr("/* fn_result */");
    }

    fn emitAssignment(self: *CEmitter, a: *const ast.Assignment) !void {
        try self.writeIndent();
        try self.emitExpr(a.target);
        switch (a.op) {
            .assign => try self.writeStr(" = "),
            .add => try self.writeStr(" += "),
            .sub => try self.writeStr(" -= "),
            .mul => try self.writeStr(" *= "),
            .div => try self.writeStr(" /= "),
        }
        try self.emitExpr(a.value);
        try self.writeStr(";\n");
    }

    fn emitIfStmt(self: *CEmitter, ifs: *const ast.IfStmt) !void {
        try self.writeIndent();
        try self.writeStr("if (");
        try self.emitExpr(ifs.condition);
        try self.writeStr(") {\n");
        self.indent_level += 1;
        try self.emitBlock(&ifs.then_block);
        self.indent_level -= 1;

        for (ifs.elif_branches) |*elif| {
            try self.writeIndent();
            try self.writeStr("} else if (");
            try self.emitExpr(elif.condition);
            try self.writeStr(") {\n");
            self.indent_level += 1;
            try self.emitBlock(&elif.block);
            self.indent_level -= 1;
        }

        if (ifs.else_block) |*eb| {
            try self.writeIndent();
            try self.writeStr("} else {\n");
            self.indent_level += 1;
            try self.emitBlock(eb);
            self.indent_level -= 1;
        }

        try self.writeIndent();
        try self.writeStr("}\n");
    }

    fn emitWhileStmt(self: *CEmitter, ws: *const ast.WhileStmt) !void {
        try self.writeIndent();
        try self.writeStr("while (");
        try self.emitExpr(ws.condition);
        try self.writeStr(") {\n");
        self.indent_level += 1;
        try self.emitBlock(&ws.body);
        self.indent_level -= 1;
        try self.writeIndent();
        try self.writeStr("}\n");
    }

    fn emitReturnStmt(self: *CEmitter, rs: *const ast.ReturnStmt) !void {
        try self.writeIndent();
        if (rs.value) |val| {
            try self.writeStr("return ");
            try self.emitExpr(val);
            try self.writeStr(";\n");
        } else {
            try self.writeStr("return;\n");
        }
    }

    fn emitForStmt(self: *CEmitter, fs: *const ast.ForStmt) !void {
        // for loops over collections — not yet fully supported
        // emit a comment placeholder
        _ = fs;
        try self.writeIndent();
        try self.writeStr("/* for loop not yet supported in codegen */\n");
    }

    fn emitMatchStmt(self: *CEmitter, m: *const ast.MatchExpr) !void {
        // match as statement — emit as if/else chain for now
        try self.emitMatchAsIfChain(m, true);
    }

    // ---------------------------------------------------------------
    // expressions
    // ---------------------------------------------------------------

    fn emitExpr(self: *CEmitter, expr: *const ast.Expr) !void {
        switch (expr.kind) {
            .int_lit => |lit| try self.writeStr(lit),
            .float_lit => |lit| try self.writeStr(lit),
            .string_lit => |lit| try self.emitStringLit(lit),
            .bool_lit => |b| try self.writeStr(if (b) "true" else "false"),
            .none_lit => try self.writeStr("/* None */"),
            .ident => |name| try self.writeStr(name),
            .self_expr => try self.writeStr("self"),
            .binary => |bin| try self.emitBinary(&bin),
            .unary => |un| try self.emitUnary(&un),
            .call => |call| try self.emitCall(&call),
            .method_call => |mc| try self.emitMethodCall(&mc),
            .field_access => |fa| try self.emitFieldAccess(&fa),
            .index => |idx| {
                // index expressions on collections — not yet supported
                _ = idx;
                try self.writeStr("/* index not yet supported */");
            },
            .grouped => |inner| {
                try self.writeByte('(');
                try self.emitExpr(inner);
                try self.writeByte(')');
            },
            .if_expr => |if_e| try self.emitIfExpr(&if_e),
            .match_expr => |m| try self.emitMatchAsIfChain(&m, false),
            .string_interp => |interp| try self.emitStringInterp(&interp),
            .lambda => |_| try self.writeStr("/* lambda not yet supported */"),
            .list => |_| try self.writeStr("/* list not yet supported */"),
            .map => |_| try self.writeStr("/* map not yet supported */"),
            .set => |_| try self.writeStr("/* set not yet supported */"),
            .tuple => |_| try self.writeStr("/* tuple not yet supported */"),
            .unwrap => |_| try self.writeStr("/* unwrap not yet supported */"),
            .try_expr => |_| try self.writeStr("/* try not yet supported */"),
            .spawn_expr => |_| try self.writeStr("/* spawn not yet supported */"),
            .await_expr => |_| try self.writeStr("/* await not yet supported */"),
            .err => {},
        }
    }

    fn emitStringLit(self: *CEmitter, lit: []const u8) !void {
        try self.writeStr("FORGE_STRING_LIT(\"");
        try self.writeEscapedString(lit);
        try self.writeStr("\")");
    }

    fn emitBinary(self: *CEmitter, bin: *const ast.BinaryExpr) !void {
        // string operations need special handling
        const is_string_op = self.isStringExpr(bin.left);

        if (is_string_op) {
            switch (bin.op) {
                .add => {
                    try self.writeStr("forge_string_concat(");
                    try self.emitExpr(bin.left);
                    try self.writeStr(", ");
                    try self.emitExpr(bin.right);
                    try self.writeByte(')');
                    return;
                },
                .eq => return self.emitStringCmp("forge_string_eq", bin),
                .neq => return self.emitStringCmp("forge_string_neq", bin),
                .lt => return self.emitStringCmp("forge_string_lt", bin),
                .gt => return self.emitStringCmp("forge_string_gt", bin),
                .lte => return self.emitStringCmp("forge_string_lte", bin),
                .gte => return self.emitStringCmp("forge_string_gte", bin),
                else => {},
            }
        }

        try self.writeByte('(');
        try self.emitExpr(bin.left);
        try self.writeStr(switch (bin.op) {
            .add => " + ",
            .sub => " - ",
            .mul => " * ",
            .div => " / ",
            .mod => " % ",
            .eq => " == ",
            .neq => " != ",
            .lt => " < ",
            .gt => " > ",
            .lte => " <= ",
            .gte => " >= ",
            .@"and" => " && ",
            .@"or" => " || ",
            .pipe => " /* pipe */ ",
        });
        try self.emitExpr(bin.right);
        try self.writeByte(')');
    }

    fn emitStringCmp(self: *CEmitter, func: []const u8, bin: *const ast.BinaryExpr) !void {
        try self.writeStr(func);
        try self.writeByte('(');
        try self.emitExpr(bin.left);
        try self.writeStr(", ");
        try self.emitExpr(bin.right);
        try self.writeByte(')');
    }

    /// heuristic: is this expression a string? used to choose between
    /// C operators and forge_string_* functions. not perfect — the real
    /// solution is storing resolved types on AST nodes, but this works
    /// for the bootstrap compiler.
    fn isStringExpr(_: *const CEmitter, expr: *const ast.Expr) bool {
        return switch (expr.kind) {
            .string_lit, .string_interp => true,
            // a call to a function returning String — we can't easily tell
            // without storing types on the AST, so we're conservative
            else => false,
        };
    }

    fn emitUnary(self: *CEmitter, un: *const ast.UnaryExpr) !void {
        switch (un.op) {
            .negate => {
                try self.writeStr("(-");
                try self.emitExpr(un.operand);
                try self.writeByte(')');
            },
            .not => {
                try self.writeStr("(!");
                try self.emitExpr(un.operand);
                try self.writeByte(')');
            },
        }
    }

    fn emitCall(self: *CEmitter, call: *const ast.CallExpr) !void {
        const name = switch (call.callee.kind) {
            .ident => |n| n,
            else => {
                // indirect calls — emit as-is
                try self.emitExpr(call.callee);
                try self.emitArgList(call.args);
                return;
            },
        };

        // print() → forge_print()
        if (std.mem.eql(u8, name, "print")) {
            try self.writeStr("forge_print(");
            if (call.args.len > 0) {
                try self.emitExpr(call.args[0].value);
            }
            try self.writeByte(')');
            return;
        }

        // struct constructor: Name(args) → (Name){ .field1 = arg1, ... }
        if (self.type_table.lookup(name)) |tid| {
            if (self.type_table.get(tid)) |ty| {
                switch (ty) {
                    .@"struct" => |s| {
                        try self.writeByte('(');
                        try self.writeStr(name);
                        try self.writeStr("){ ");
                        for (s.fields, 0..) |field, i| {
                            if (i > 0) try self.writeStr(", ");
                            try self.writeByte('.');
                            try self.writeStr(field.name);
                            try self.writeStr(" = ");
                            if (i < call.args.len) {
                                try self.emitExpr(call.args[i].value);
                            }
                        }
                        try self.writeStr(" }");
                        return;
                    },
                    else => {},
                }
            }
        }

        // regular function call
        try self.writeStr(name);
        try self.emitArgList(call.args);
    }

    fn emitMethodCall(self: *CEmitter, mc: *const ast.MethodCallExpr) !void {
        // methods are emitted as TypeName_method(receiver, args...)
        // we need the receiver's type name — for now, emit a placeholder
        // until PR 5 adds proper method support
        try self.writeStr("/* method call: ");
        try self.writeStr(mc.method);
        try self.writeStr(" */");
    }

    fn emitFieldAccess(self: *CEmitter, fa: *const ast.FieldAccess) !void {
        try self.emitExpr(fa.object);
        try self.writeByte('.');
        try self.writeStr(fa.field);
    }

    fn emitArgList(self: *CEmitter, args: []const ast.Arg) !void {
        try self.writeByte('(');
        for (args, 0..) |arg, i| {
            if (i > 0) try self.writeStr(", ");
            try self.emitExpr(arg.value);
        }
        try self.writeByte(')');
    }

    fn emitIfExpr(self: *CEmitter, if_e: *const ast.IfExpr) !void {
        // ternary: condition ? then : else
        // for elif chains, nest them
        try self.writeByte('(');
        try self.emitExpr(if_e.condition);
        try self.writeStr(" ? ");
        try self.emitExpr(if_e.then_expr);
        try self.writeStr(" : ");
        if (if_e.elif_branches.len > 0) {
            // nested ternaries for elif
            for (if_e.elif_branches) |*elif| {
                try self.emitExpr(elif.condition);
                try self.writeStr(" ? ");
                try self.emitExpr(elif.expr);
                try self.writeStr(" : ");
            }
        }
        try self.emitExpr(if_e.else_expr);
        try self.writeByte(')');
    }

    fn emitStringInterp(self: *CEmitter, interp: *const ast.StringInterp) !void {
        // string interpolation: "hello {name}!" → forge_string_concat chain
        // count non-empty parts
        var part_count: usize = 0;
        for (interp.parts) |_| part_count += 1;

        if (part_count == 0) {
            try self.writeStr("forge_string_empty");
            return;
        }
        if (part_count == 1) {
            try self.emitStringPart(&interp.parts[0]);
            return;
        }

        // nested concat calls: concat(concat(a, b), c)
        var opens: usize = 0;
        for (interp.parts[0 .. part_count - 1]) |_| {
            if (opens > 0) {
                try self.writeStr("forge_string_concat(");
            }
            opens += 1;
        }

        // emit first part
        try self.emitStringPart(&interp.parts[0]);

        // emit rest with concat
        for (interp.parts[1..]) |*part| {
            try self.writeStr(", ");
            try self.emitStringPart(part);
            try self.writeByte(')');
        }
    }

    fn emitStringPart(self: *CEmitter, part: *const ast.StringPart) !void {
        switch (part.*) {
            .literal => |lit| {
                try self.writeStr("FORGE_STRING_LIT(\"");
                try self.writeEscapedString(lit);
                try self.writeStr("\")");
            },
            .expr => |expr| {
                // need to convert the expression to string
                try self.emitExprAsString(expr);
            },
        }
    }

    /// emit an expression converted to forge_string_t.
    fn emitExprAsString(self: *CEmitter, expr: *const ast.Expr) !void {
        switch (expr.kind) {
            .string_lit => |lit| try self.emitStringLit(lit),
            .string_interp => |interp| try self.emitStringInterp(&interp),
            .ident => |_| {
                // we don't know the type here — wrap in forge_int_to_string as guess
                // TODO: use stored type info to choose the right conversion
                try self.writeStr("forge_int_to_string(");
                try self.emitExpr(expr);
                try self.writeByte(')');
            },
            .field_access => |_| {
                try self.writeStr("forge_int_to_string(");
                try self.emitExpr(expr);
                try self.writeByte(')');
            },
            .int_lit => |_| {
                try self.writeStr("forge_int_to_string(");
                try self.emitExpr(expr);
                try self.writeByte(')');
            },
            .float_lit => |_| {
                try self.writeStr("forge_float_to_string(");
                try self.emitExpr(expr);
                try self.writeByte(')');
            },
            .bool_lit => |_| {
                try self.writeStr("forge_bool_to_string(");
                try self.emitExpr(expr);
                try self.writeByte(')');
            },
            else => {
                // fallback — just emit the expression and hope it's a string
                try self.emitExpr(expr);
            },
        }
    }

    fn emitMatchAsIfChain(self: *CEmitter, m: *const ast.MatchExpr, is_stmt: bool) !void {
        if (m.arms.len == 0) return;

        if (is_stmt) {
            // emit subject into a temp variable
            try self.writeIndent();
            try self.writeStr("{\n");
            self.indent_level += 1;
        }

        for (m.arms, 0..) |*arm, i| {
            const is_last = i == m.arms.len - 1;
            const is_wildcard = arm.pattern.kind == .wildcard or arm.pattern.kind == .binding;

            if (is_stmt) {
                if (i == 0) {
                    if (is_wildcard and is_last) {
                        // single wildcard arm — just emit the body
                    } else if (!is_wildcard) {
                        try self.writeIndent();
                        try self.writeStr("if (");
                        try self.emitPatternCondition(m.subject, &arm.pattern);
                        try self.writeStr(") {\n");
                        self.indent_level += 1;
                    }
                } else if (is_wildcard and is_last) {
                    try self.writeIndent();
                    try self.writeStr("} else {\n");
                    self.indent_level += 1;
                } else {
                    try self.writeIndent();
                    try self.writeStr("} else if (");
                    try self.emitPatternCondition(m.subject, &arm.pattern);
                    try self.writeStr(") {\n");
                    self.indent_level += 1;
                }

                // emit binding if present
                if (arm.pattern.kind == .binding) {
                    try self.writeIndent();
                    try self.emitInferredType(m.subject);
                    try self.writeByte(' ');
                    try self.writeStr(arm.pattern.kind.binding);
                    try self.writeStr(" = ");
                    try self.emitExpr(m.subject);
                    try self.writeStr(";\n");
                }

                switch (arm.body) {
                    .expr => |e| {
                        try self.writeIndent();
                        try self.emitExpr(e);
                        try self.writeStr(";\n");
                    },
                    .block => |*blk| try self.emitBlock(blk),
                }

                if (!is_wildcard or !is_last) {
                    self.indent_level -= 1;
                } else if (i > 0) {
                    self.indent_level -= 1;
                    try self.writeIndent();
                    try self.writeStr("}\n");
                }
            } else {
                // match as expression — emit as ternary chain
                if (i > 0) try self.writeStr(" : ");
                if (!is_wildcard or !is_last) {
                    try self.writeStr("(");
                    try self.emitPatternCondition(m.subject, &arm.pattern);
                    try self.writeStr(" ? ");
                }
                switch (arm.body) {
                    .expr => |e| try self.emitExpr(e),
                    .block => try self.writeStr("/* block in match expr */"),
                }
                if (!is_wildcard or !is_last) {
                    try self.writeByte(')');
                }
            }
        }

        if (is_stmt) {
            // close the last if block if needed
            if (m.arms.len > 0) {
                const last = m.arms[m.arms.len - 1];
                const last_is_wildcard = last.pattern.kind == .wildcard or last.pattern.kind == .binding;
                if (!last_is_wildcard) {
                    try self.writeIndent();
                    try self.writeStr("}\n");
                }
            }
            self.indent_level -= 1;
            try self.writeIndent();
            try self.writeStr("}\n");
        }
    }

    fn emitPatternCondition(self: *CEmitter, subject: *const ast.Expr, pattern: *const ast.Pattern) !void {
        switch (pattern.kind) {
            .wildcard, .binding => try self.writeStr("1"),
            .int_lit => |lit| {
                try self.emitExpr(subject);
                try self.writeStr(" == ");
                try self.writeStr(lit);
            },
            .float_lit => |lit| {
                try self.emitExpr(subject);
                try self.writeStr(" == ");
                try self.writeStr(lit);
            },
            .string_lit => |lit| {
                try self.writeStr("forge_string_eq(");
                try self.emitExpr(subject);
                try self.writeStr(", FORGE_STRING_LIT(\"");
                try self.writeEscapedString(lit);
                try self.writeStr("\"))");
            },
            .bool_lit => |b| {
                try self.emitExpr(subject);
                try self.writeStr(if (b) " == true" else " == false");
            },
            .none_lit => try self.writeStr("0 /* None pattern */"),
            .variant => |vp| {
                try self.emitExpr(subject);
                try self.writeStr(".tag == ");
                try self.writeStr(vp.type_name);
                try self.writeStr("_TAG_");
                try self.writeStr(vp.variant);
            },
            .tuple => |_| try self.writeStr("1 /* tuple pattern */"),
        }
    }

    // ---------------------------------------------------------------
    // type emission
    // ---------------------------------------------------------------

    fn emitTypeExpr(self: *CEmitter, te: *const ast.TypeExpr) !void {
        switch (te.kind) {
            .named => |name| try self.emitNamedType(name),
            .generic => |g| {
                // generic types — emit the base name (should be instantiated)
                try self.writeStr(g.name);
            },
            .optional => try self.writeStr("/* optional */"),
            .result => try self.writeStr("/* result */"),
            .tuple => try self.writeStr("/* tuple type */"),
            .fn_type => try self.writeStr("/* fn type */"),
        }
    }

    fn emitNamedType(self: *CEmitter, name: []const u8) !void {
        try self.writeStr(mapType(name));
    }

    /// emit a C type for a TypeId from the type table.
    pub fn emitCType(self: *CEmitter, tid: TypeId) !void {
        try self.writeStr(mapTypeId(tid));

        // user-defined types — look up the name
        if (tid.index() >= TypeId.first_user) {
            if (self.type_table.get(tid)) |ty| {
                switch (ty) {
                    .@"struct" => |s| {
                        try self.writeStr(s.name);
                        return;
                    },
                    .@"enum" => |e| {
                        try self.writeStr(e.name);
                        return;
                    },
                    else => {},
                }
            }
        }
    }

    // ---------------------------------------------------------------
    // type mapping
    // ---------------------------------------------------------------

    /// map a forge type name to a C type string.
    pub fn mapType(name: []const u8) []const u8 {
        if (std.mem.eql(u8, name, "Int")) return "int64_t";
        if (std.mem.eql(u8, name, "UInt")) return "uint64_t";
        if (std.mem.eql(u8, name, "Float")) return "double";
        if (std.mem.eql(u8, name, "Bool")) return "bool";
        if (std.mem.eql(u8, name, "String")) return "forge_string_t";
        if (std.mem.eql(u8, name, "Bytes")) return "uint8_t*";
        if (std.mem.eql(u8, name, "Void")) return "void";
        if (std.mem.eql(u8, name, "Int8")) return "int8_t";
        if (std.mem.eql(u8, name, "Int16")) return "int16_t";
        if (std.mem.eql(u8, name, "Int32")) return "int32_t";
        if (std.mem.eql(u8, name, "Int64")) return "int64_t";
        if (std.mem.eql(u8, name, "UInt8")) return "uint8_t";
        if (std.mem.eql(u8, name, "UInt16")) return "uint16_t";
        if (std.mem.eql(u8, name, "UInt32")) return "uint32_t";
        if (std.mem.eql(u8, name, "UInt64")) return "uint64_t";
        // user-defined type — use the name as-is (should be typedef'd)
        return name;
    }

    /// map a TypeId to a C type string for builtin types.
    /// returns empty string for user-defined types (caller handles those).
    pub fn mapTypeId(tid: TypeId) []const u8 {
        return switch (tid) {
            .int => "int64_t",
            .uint => "uint64_t",
            .float => "double",
            .bool => "bool",
            .string => "forge_string_t",
            .bytes => "uint8_t*",
            .void => "void",
            .int8 => "int8_t",
            .int16 => "int16_t",
            .int32 => "int32_t",
            .int64 => "int64_t",
            .uint8 => "uint8_t",
            .uint16 => "uint16_t",
            .uint32 => "uint32_t",
            .uint64 => "uint64_t",
            .err => "/* error */",
            _ => "", // user-defined — caller handles
        };
    }

    // ---------------------------------------------------------------
    // output helpers
    // ---------------------------------------------------------------

    fn writeStr(self: *CEmitter, s: []const u8) !void {
        try self.output.appendSlice(self.allocator, s);
    }

    fn writeByte(self: *CEmitter, b: u8) !void {
        try self.output.append(self.allocator, b);
    }

    fn writeFmt(self: *CEmitter, comptime fmt: []const u8, args: anytype) !void {
        var buf: [256]u8 = undefined;
        const s = std.fmt.bufPrint(&buf, fmt, args) catch return;
        try self.output.appendSlice(self.allocator, s);
    }

    fn writeIndent(self: *CEmitter) !void {
        var i: u32 = 0;
        while (i < self.indent_level) : (i += 1) {
            try self.output.appendSlice(self.allocator, "    ");
        }
    }

    fn writeEscapedString(self: *CEmitter, s: []const u8) !void {
        for (s) |c| {
            switch (c) {
                '\\' => try self.output.appendSlice(self.allocator, "\\\\"),
                '"' => try self.output.appendSlice(self.allocator, "\\\""),
                '\n' => try self.output.appendSlice(self.allocator, "\\n"),
                '\r' => try self.output.appendSlice(self.allocator, "\\r"),
                '\t' => try self.output.appendSlice(self.allocator, "\\t"),
                else => try self.output.append(self.allocator, c),
            }
        }
    }
};

// ---------------------------------------------------------------
// tests
// ---------------------------------------------------------------

test "mapType maps forge primitives to C types" {
    try std.testing.expectEqualStrings("int64_t", CEmitter.mapType("Int"));
    try std.testing.expectEqualStrings("uint64_t", CEmitter.mapType("UInt"));
    try std.testing.expectEqualStrings("double", CEmitter.mapType("Float"));
    try std.testing.expectEqualStrings("bool", CEmitter.mapType("Bool"));
    try std.testing.expectEqualStrings("forge_string_t", CEmitter.mapType("String"));
    try std.testing.expectEqualStrings("void", CEmitter.mapType("Void"));
    try std.testing.expectEqualStrings("int8_t", CEmitter.mapType("Int8"));
    try std.testing.expectEqualStrings("uint64_t", CEmitter.mapType("UInt64"));
}

test "mapType passes through user-defined types" {
    try std.testing.expectEqualStrings("Point", CEmitter.mapType("Point"));
    try std.testing.expectEqualStrings("MyStruct", CEmitter.mapType("MyStruct"));
}

test "mapTypeId maps builtin type ids" {
    try std.testing.expectEqualStrings("int64_t", CEmitter.mapTypeId(.int));
    try std.testing.expectEqualStrings("double", CEmitter.mapTypeId(.float));
    try std.testing.expectEqualStrings("bool", CEmitter.mapTypeId(.bool));
    try std.testing.expectEqualStrings("forge_string_t", CEmitter.mapTypeId(.string));
    try std.testing.expectEqualStrings("void", CEmitter.mapTypeId(.void));
}

test "mapTypeId returns empty for user-defined types" {
    const user_id = TypeId.fromIndex(TypeId.first_user);
    try std.testing.expectEqualStrings("", CEmitter.mapTypeId(user_id));
}

test "emitter init and deinit" {
    var table = try TypeTable.init(std.testing.allocator);
    defer table.deinit();

    var emitter = CEmitter.init(std.testing.allocator, &table);
    defer emitter.deinit();

    try std.testing.expectEqual(@as(usize, 0), emitter.getOutput().len);
}

test "emitPreamble writes includes" {
    var table = try TypeTable.init(std.testing.allocator);
    defer table.deinit();

    var emitter = CEmitter.init(std.testing.allocator, &table);
    defer emitter.deinit();

    try emitter.emitPreamble();
    const output = emitter.getOutput();
    try std.testing.expect(std.mem.indexOf(u8, output, "forge_runtime.h") != null);
}
